package com.guobao.dto.log;

import java.util.Date;

public class Lkservertranslog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.Sid
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.TranNo
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private String tranno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.sourceCode
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private String sourcecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.orderNo
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private String orderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.businessType
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private String businesstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.category
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private String category;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.requestTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private Date requesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.responseTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private Date responsetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.usedTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private Float usedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.state
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkservertranslog.makeDate
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    private Date makedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.Sid
     *
     * @return the value of lkservertranslog.Sid
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.Sid
     *
     * @param sid the value for lkservertranslog.Sid
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.TranNo
     *
     * @return the value of lkservertranslog.TranNo
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public String getTranno() {
        return tranno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.TranNo
     *
     * @param tranno the value for lkservertranslog.TranNo
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setTranno(String tranno) {
        this.tranno = tranno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.sourceCode
     *
     * @return the value of lkservertranslog.sourceCode
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public String getSourcecode() {
        return sourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.sourceCode
     *
     * @param sourcecode the value for lkservertranslog.sourceCode
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setSourcecode(String sourcecode) {
        this.sourcecode = sourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.orderNo
     *
     * @return the value of lkservertranslog.orderNo
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.orderNo
     *
     * @param orderno the value for lkservertranslog.orderNo
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.businessType
     *
     * @return the value of lkservertranslog.businessType
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.businessType
     *
     * @param businesstype the value for lkservertranslog.businessType
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.category
     *
     * @return the value of lkservertranslog.category
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.category
     *
     * @param category the value for lkservertranslog.category
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.requestTime
     *
     * @return the value of lkservertranslog.requestTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.requestTime
     *
     * @param requesttime the value for lkservertranslog.requestTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.responseTime
     *
     * @return the value of lkservertranslog.responseTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public Date getResponsetime() {
        return responsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.responseTime
     *
     * @param responsetime the value for lkservertranslog.responseTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setResponsetime(Date responsetime) {
        this.responsetime = responsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.usedTime
     *
     * @return the value of lkservertranslog.usedTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public Float getUsedtime() {
        return usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.usedTime
     *
     * @param usedtime the value for lkservertranslog.usedTime
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setUsedtime(Float usedtime) {
        this.usedtime = usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.state
     *
     * @return the value of lkservertranslog.state
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.state
     *
     * @param state the value for lkservertranslog.state
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkservertranslog.makeDate
     *
     * @return the value of lkservertranslog.makeDate
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkservertranslog.makeDate
     *
     * @param makedate the value for lkservertranslog.makeDate
     *
     * @mbg.generated Sun Apr 01 19:17:40 CST 2018
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }
}