package com.guobao.dto.report;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LLAccidentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public LLAccidentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAccnoIsNull() {
            addCriterion("ACCNO is null");
            return (Criteria) this;
        }

        public Criteria andAccnoIsNotNull() {
            addCriterion("ACCNO is not null");
            return (Criteria) this;
        }

        public Criteria andAccnoEqualTo(String value) {
            addCriterion("ACCNO =", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoNotEqualTo(String value) {
            addCriterion("ACCNO <>", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoGreaterThan(String value) {
            addCriterion("ACCNO >", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoGreaterThanOrEqualTo(String value) {
            addCriterion("ACCNO >=", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoLessThan(String value) {
            addCriterion("ACCNO <", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoLessThanOrEqualTo(String value) {
            addCriterion("ACCNO <=", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoLike(String value) {
            addCriterion("ACCNO like", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoNotLike(String value) {
            addCriterion("ACCNO not like", value, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoIn(List<String> values) {
            addCriterion("ACCNO in", values, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoNotIn(List<String> values) {
            addCriterion("ACCNO not in", values, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoBetween(String value1, String value2) {
            addCriterion("ACCNO between", value1, value2, "accno");
            return (Criteria) this;
        }

        public Criteria andAccnoNotBetween(String value1, String value2) {
            addCriterion("ACCNO not between", value1, value2, "accno");
            return (Criteria) this;
        }

        public Criteria andAccdateIsNull() {
            addCriterion("ACCDATE is null");
            return (Criteria) this;
        }

        public Criteria andAccdateIsNotNull() {
            addCriterion("ACCDATE is not null");
            return (Criteria) this;
        }

        public Criteria andAccdateEqualTo(Date value) {
            addCriterionForJDBCDate("ACCDATE =", value, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ACCDATE <>", value, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateGreaterThan(Date value) {
            addCriterionForJDBCDate("ACCDATE >", value, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACCDATE >=", value, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateLessThan(Date value) {
            addCriterionForJDBCDate("ACCDATE <", value, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACCDATE <=", value, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateIn(List<Date> values) {
            addCriterionForJDBCDate("ACCDATE in", values, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ACCDATE not in", values, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACCDATE between", value1, value2, "accdate");
            return (Criteria) this;
        }

        public Criteria andAccdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACCDATE not between", value1, value2, "accdate");
            return (Criteria) this;
        }

        public Criteria andAcctypeIsNull() {
            addCriterion("ACCTYPE is null");
            return (Criteria) this;
        }

        public Criteria andAcctypeIsNotNull() {
            addCriterion("ACCTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAcctypeEqualTo(String value) {
            addCriterion("ACCTYPE =", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeNotEqualTo(String value) {
            addCriterion("ACCTYPE <>", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeGreaterThan(String value) {
            addCriterion("ACCTYPE >", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCTYPE >=", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeLessThan(String value) {
            addCriterion("ACCTYPE <", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeLessThanOrEqualTo(String value) {
            addCriterion("ACCTYPE <=", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeLike(String value) {
            addCriterion("ACCTYPE like", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeNotLike(String value) {
            addCriterion("ACCTYPE not like", value, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeIn(List<String> values) {
            addCriterion("ACCTYPE in", values, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeNotIn(List<String> values) {
            addCriterion("ACCTYPE not in", values, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeBetween(String value1, String value2) {
            addCriterion("ACCTYPE between", value1, value2, "acctype");
            return (Criteria) this;
        }

        public Criteria andAcctypeNotBetween(String value1, String value2) {
            addCriterion("ACCTYPE not between", value1, value2, "acctype");
            return (Criteria) this;
        }

        public Criteria andAccsubjectIsNull() {
            addCriterion("ACCSUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andAccsubjectIsNotNull() {
            addCriterion("ACCSUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andAccsubjectEqualTo(String value) {
            addCriterion("ACCSUBJECT =", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectNotEqualTo(String value) {
            addCriterion("ACCSUBJECT <>", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectGreaterThan(String value) {
            addCriterion("ACCSUBJECT >", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectGreaterThanOrEqualTo(String value) {
            addCriterion("ACCSUBJECT >=", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectLessThan(String value) {
            addCriterion("ACCSUBJECT <", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectLessThanOrEqualTo(String value) {
            addCriterion("ACCSUBJECT <=", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectLike(String value) {
            addCriterion("ACCSUBJECT like", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectNotLike(String value) {
            addCriterion("ACCSUBJECT not like", value, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectIn(List<String> values) {
            addCriterion("ACCSUBJECT in", values, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectNotIn(List<String> values) {
            addCriterion("ACCSUBJECT not in", values, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectBetween(String value1, String value2) {
            addCriterion("ACCSUBJECT between", value1, value2, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccsubjectNotBetween(String value1, String value2) {
            addCriterion("ACCSUBJECT not between", value1, value2, "accsubject");
            return (Criteria) this;
        }

        public Criteria andAccdescIsNull() {
            addCriterion("ACCDESC is null");
            return (Criteria) this;
        }

        public Criteria andAccdescIsNotNull() {
            addCriterion("ACCDESC is not null");
            return (Criteria) this;
        }

        public Criteria andAccdescEqualTo(String value) {
            addCriterion("ACCDESC =", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescNotEqualTo(String value) {
            addCriterion("ACCDESC <>", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescGreaterThan(String value) {
            addCriterion("ACCDESC >", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescGreaterThanOrEqualTo(String value) {
            addCriterion("ACCDESC >=", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescLessThan(String value) {
            addCriterion("ACCDESC <", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescLessThanOrEqualTo(String value) {
            addCriterion("ACCDESC <=", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescLike(String value) {
            addCriterion("ACCDESC like", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescNotLike(String value) {
            addCriterion("ACCDESC not like", value, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescIn(List<String> values) {
            addCriterion("ACCDESC in", values, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescNotIn(List<String> values) {
            addCriterion("ACCDESC not in", values, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescBetween(String value1, String value2) {
            addCriterion("ACCDESC between", value1, value2, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccdescNotBetween(String value1, String value2) {
            addCriterion("ACCDESC not between", value1, value2, "accdesc");
            return (Criteria) this;
        }

        public Criteria andAccplaceIsNull() {
            addCriterion("ACCPLACE is null");
            return (Criteria) this;
        }

        public Criteria andAccplaceIsNotNull() {
            addCriterion("ACCPLACE is not null");
            return (Criteria) this;
        }

        public Criteria andAccplaceEqualTo(String value) {
            addCriterion("ACCPLACE =", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceNotEqualTo(String value) {
            addCriterion("ACCPLACE <>", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceGreaterThan(String value) {
            addCriterion("ACCPLACE >", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceGreaterThanOrEqualTo(String value) {
            addCriterion("ACCPLACE >=", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceLessThan(String value) {
            addCriterion("ACCPLACE <", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceLessThanOrEqualTo(String value) {
            addCriterion("ACCPLACE <=", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceLike(String value) {
            addCriterion("ACCPLACE like", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceNotLike(String value) {
            addCriterion("ACCPLACE not like", value, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceIn(List<String> values) {
            addCriterion("ACCPLACE in", values, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceNotIn(List<String> values) {
            addCriterion("ACCPLACE not in", values, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceBetween(String value1, String value2) {
            addCriterion("ACCPLACE between", value1, value2, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccplaceNotBetween(String value1, String value2) {
            addCriterion("ACCPLACE not between", value1, value2, "accplace");
            return (Criteria) this;
        }

        public Criteria andAccgradeIsNull() {
            addCriterion("ACCGRADE is null");
            return (Criteria) this;
        }

        public Criteria andAccgradeIsNotNull() {
            addCriterion("ACCGRADE is not null");
            return (Criteria) this;
        }

        public Criteria andAccgradeEqualTo(String value) {
            addCriterion("ACCGRADE =", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeNotEqualTo(String value) {
            addCriterion("ACCGRADE <>", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeGreaterThan(String value) {
            addCriterion("ACCGRADE >", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCGRADE >=", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeLessThan(String value) {
            addCriterion("ACCGRADE <", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeLessThanOrEqualTo(String value) {
            addCriterion("ACCGRADE <=", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeLike(String value) {
            addCriterion("ACCGRADE like", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeNotLike(String value) {
            addCriterion("ACCGRADE not like", value, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeIn(List<String> values) {
            addCriterion("ACCGRADE in", values, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeNotIn(List<String> values) {
            addCriterion("ACCGRADE not in", values, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeBetween(String value1, String value2) {
            addCriterion("ACCGRADE between", value1, value2, "accgrade");
            return (Criteria) this;
        }

        public Criteria andAccgradeNotBetween(String value1, String value2) {
            addCriterion("ACCGRADE not between", value1, value2, "accgrade");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("OPERATOR =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("OPERATOR <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("OPERATOR >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("OPERATOR <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("OPERATOR like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("OPERATOR not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("OPERATOR in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("OPERATOR not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("OPERATOR between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("OPERATOR not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andMngcomIsNull() {
            addCriterion("MNGCOM is null");
            return (Criteria) this;
        }

        public Criteria andMngcomIsNotNull() {
            addCriterion("MNGCOM is not null");
            return (Criteria) this;
        }

        public Criteria andMngcomEqualTo(String value) {
            addCriterion("MNGCOM =", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomNotEqualTo(String value) {
            addCriterion("MNGCOM <>", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomGreaterThan(String value) {
            addCriterion("MNGCOM >", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomGreaterThanOrEqualTo(String value) {
            addCriterion("MNGCOM >=", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomLessThan(String value) {
            addCriterion("MNGCOM <", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomLessThanOrEqualTo(String value) {
            addCriterion("MNGCOM <=", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomLike(String value) {
            addCriterion("MNGCOM like", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomNotLike(String value) {
            addCriterion("MNGCOM not like", value, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomIn(List<String> values) {
            addCriterion("MNGCOM in", values, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomNotIn(List<String> values) {
            addCriterion("MNGCOM not in", values, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomBetween(String value1, String value2) {
            addCriterion("MNGCOM between", value1, value2, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMngcomNotBetween(String value1, String value2) {
            addCriterion("MNGCOM not between", value1, value2, "mngcom");
            return (Criteria) this;
        }

        public Criteria andMakedateIsNull() {
            addCriterion("MAKEDATE is null");
            return (Criteria) this;
        }

        public Criteria andMakedateIsNotNull() {
            addCriterion("MAKEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andMakedateEqualTo(Date value) {
            addCriterionForJDBCDate("MAKEDATE =", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MAKEDATE <>", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateGreaterThan(Date value) {
            addCriterionForJDBCDate("MAKEDATE >", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MAKEDATE >=", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateLessThan(Date value) {
            addCriterionForJDBCDate("MAKEDATE <", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MAKEDATE <=", value, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateIn(List<Date> values) {
            addCriterionForJDBCDate("MAKEDATE in", values, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("MAKEDATE not in", values, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MAKEDATE between", value1, value2, "makedate");
            return (Criteria) this;
        }

        public Criteria andMakedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MAKEDATE not between", value1, value2, "makedate");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNull() {
            addCriterion("MAKETIME is null");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNotNull() {
            addCriterion("MAKETIME is not null");
            return (Criteria) this;
        }

        public Criteria andMaketimeEqualTo(String value) {
            addCriterion("MAKETIME =", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotEqualTo(String value) {
            addCriterion("MAKETIME <>", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThan(String value) {
            addCriterion("MAKETIME >", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThanOrEqualTo(String value) {
            addCriterion("MAKETIME >=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThan(String value) {
            addCriterion("MAKETIME <", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThanOrEqualTo(String value) {
            addCriterion("MAKETIME <=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLike(String value) {
            addCriterion("MAKETIME like", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotLike(String value) {
            addCriterion("MAKETIME not like", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeIn(List<String> values) {
            addCriterion("MAKETIME in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotIn(List<String> values) {
            addCriterion("MAKETIME not in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeBetween(String value1, String value2) {
            addCriterion("MAKETIME between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotBetween(String value1, String value2) {
            addCriterion("MAKETIME not between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return (Criteria) this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE =", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <>", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterionForJDBCDate("MODIFYDATE >", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE >=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <=", value, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateIn(List<Date> values) {
            addCriterionForJDBCDate("MODIFYDATE in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotIn(List<Date> values) {
            addCriterionForJDBCDate("MODIFYDATE not in", values, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MODIFYDATE between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MODIFYDATE not between", value1, value2, "modifydate");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNull() {
            addCriterion("MODIFYTIME is null");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNotNull() {
            addCriterion("MODIFYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifytimeEqualTo(String value) {
            addCriterion("MODIFYTIME =", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotEqualTo(String value) {
            addCriterion("MODIFYTIME <>", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThan(String value) {
            addCriterion("MODIFYTIME >", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYTIME >=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThan(String value) {
            addCriterion("MODIFYTIME <", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThanOrEqualTo(String value) {
            addCriterion("MODIFYTIME <=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLike(String value) {
            addCriterion("MODIFYTIME like", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotLike(String value) {
            addCriterion("MODIFYTIME not like", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIn(List<String> values) {
            addCriterion("MODIFYTIME in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotIn(List<String> values) {
            addCriterion("MODIFYTIME not in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeBetween(String value1, String value2) {
            addCriterion("MODIFYTIME between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotBetween(String value1, String value2) {
            addCriterion("MODIFYTIME not between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNull() {
            addCriterion("RPTNO is null");
            return (Criteria) this;
        }

        public Criteria andRptnoIsNotNull() {
            addCriterion("RPTNO is not null");
            return (Criteria) this;
        }

        public Criteria andRptnoEqualTo(String value) {
            addCriterion("RPTNO =", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotEqualTo(String value) {
            addCriterion("RPTNO <>", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThan(String value) {
            addCriterion("RPTNO >", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoGreaterThanOrEqualTo(String value) {
            addCriterion("RPTNO >=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThan(String value) {
            addCriterion("RPTNO <", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLessThanOrEqualTo(String value) {
            addCriterion("RPTNO <=", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoLike(String value) {
            addCriterion("RPTNO like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotLike(String value) {
            addCriterion("RPTNO not like", value, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoIn(List<String> values) {
            addCriterion("RPTNO in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotIn(List<String> values) {
            addCriterion("RPTNO not in", values, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoBetween(String value1, String value2) {
            addCriterion("RPTNO between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andRptnoNotBetween(String value1, String value2) {
            addCriterion("RPTNO not between", value1, value2, "rptno");
            return (Criteria) this;
        }

        public Criteria andCustomernoIsNull() {
            addCriterion("CUSTOMERNO is null");
            return (Criteria) this;
        }

        public Criteria andCustomernoIsNotNull() {
            addCriterion("CUSTOMERNO is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernoEqualTo(String value) {
            addCriterion("CUSTOMERNO =", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotEqualTo(String value) {
            addCriterion("CUSTOMERNO <>", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoGreaterThan(String value) {
            addCriterion("CUSTOMERNO >", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMERNO >=", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLessThan(String value) {
            addCriterion("CUSTOMERNO <", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMERNO <=", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLike(String value) {
            addCriterion("CUSTOMERNO like", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotLike(String value) {
            addCriterion("CUSTOMERNO not like", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoIn(List<String> values) {
            addCriterion("CUSTOMERNO in", values, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotIn(List<String> values) {
            addCriterion("CUSTOMERNO not in", values, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoBetween(String value1, String value2) {
            addCriterion("CUSTOMERNO between", value1, value2, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotBetween(String value1, String value2) {
            addCriterion("CUSTOMERNO not between", value1, value2, "customerno");
            return (Criteria) this;
        }

        public Criteria andAccreasonIsNull() {
            addCriterion("ACCREASON is null");
            return (Criteria) this;
        }

        public Criteria andAccreasonIsNotNull() {
            addCriterion("ACCREASON is not null");
            return (Criteria) this;
        }

        public Criteria andAccreasonEqualTo(String value) {
            addCriterion("ACCREASON =", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonNotEqualTo(String value) {
            addCriterion("ACCREASON <>", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonGreaterThan(String value) {
            addCriterion("ACCREASON >", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonGreaterThanOrEqualTo(String value) {
            addCriterion("ACCREASON >=", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonLessThan(String value) {
            addCriterion("ACCREASON <", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonLessThanOrEqualTo(String value) {
            addCriterion("ACCREASON <=", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonLike(String value) {
            addCriterion("ACCREASON like", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonNotLike(String value) {
            addCriterion("ACCREASON not like", value, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonIn(List<String> values) {
            addCriterion("ACCREASON in", values, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonNotIn(List<String> values) {
            addCriterion("ACCREASON not in", values, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonBetween(String value1, String value2) {
            addCriterion("ACCREASON between", value1, value2, "accreason");
            return (Criteria) this;
        }

        public Criteria andAccreasonNotBetween(String value1, String value2) {
            addCriterion("ACCREASON not between", value1, value2, "accreason");
            return (Criteria) this;
        }

        public Criteria andDeathdateIsNull() {
            addCriterion("DEATHDATE is null");
            return (Criteria) this;
        }

        public Criteria andDeathdateIsNotNull() {
            addCriterion("DEATHDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDeathdateEqualTo(Date value) {
            addCriterionForJDBCDate("DEATHDATE =", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("DEATHDATE <>", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateGreaterThan(Date value) {
            addCriterionForJDBCDate("DEATHDATE >", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DEATHDATE >=", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateLessThan(Date value) {
            addCriterionForJDBCDate("DEATHDATE <", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DEATHDATE <=", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateIn(List<Date> values) {
            addCriterionForJDBCDate("DEATHDATE in", values, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("DEATHDATE not in", values, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DEATHDATE between", value1, value2, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DEATHDATE not between", value1, value2, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateIsNull() {
            addCriterion("DEFORMITYDATE is null");
            return (Criteria) this;
        }

        public Criteria andDeformitydateIsNotNull() {
            addCriterion("DEFORMITYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDeformitydateEqualTo(Date value) {
            addCriterionForJDBCDate("DEFORMITYDATE =", value, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("DEFORMITYDATE <>", value, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateGreaterThan(Date value) {
            addCriterionForJDBCDate("DEFORMITYDATE >", value, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DEFORMITYDATE >=", value, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateLessThan(Date value) {
            addCriterionForJDBCDate("DEFORMITYDATE <", value, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DEFORMITYDATE <=", value, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateIn(List<Date> values) {
            addCriterionForJDBCDate("DEFORMITYDATE in", values, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateNotIn(List<Date> values) {
            addCriterionForJDBCDate("DEFORMITYDATE not in", values, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DEFORMITYDATE between", value1, value2, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andDeformitydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DEFORMITYDATE not between", value1, value2, "deformitydate");
            return (Criteria) this;
        }

        public Criteria andAccresult1IsNull() {
            addCriterion("ACCRESULT1 is null");
            return (Criteria) this;
        }

        public Criteria andAccresult1IsNotNull() {
            addCriterion("ACCRESULT1 is not null");
            return (Criteria) this;
        }

        public Criteria andAccresult1EqualTo(String value) {
            addCriterion("ACCRESULT1 =", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1NotEqualTo(String value) {
            addCriterion("ACCRESULT1 <>", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1GreaterThan(String value) {
            addCriterion("ACCRESULT1 >", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1GreaterThanOrEqualTo(String value) {
            addCriterion("ACCRESULT1 >=", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1LessThan(String value) {
            addCriterion("ACCRESULT1 <", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1LessThanOrEqualTo(String value) {
            addCriterion("ACCRESULT1 <=", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1Like(String value) {
            addCriterion("ACCRESULT1 like", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1NotLike(String value) {
            addCriterion("ACCRESULT1 not like", value, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1In(List<String> values) {
            addCriterion("ACCRESULT1 in", values, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1NotIn(List<String> values) {
            addCriterion("ACCRESULT1 not in", values, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1Between(String value1, String value2) {
            addCriterion("ACCRESULT1 between", value1, value2, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult1NotBetween(String value1, String value2) {
            addCriterion("ACCRESULT1 not between", value1, value2, "accresult1");
            return (Criteria) this;
        }

        public Criteria andAccresult2IsNull() {
            addCriterion("ACCRESULT2 is null");
            return (Criteria) this;
        }

        public Criteria andAccresult2IsNotNull() {
            addCriterion("ACCRESULT2 is not null");
            return (Criteria) this;
        }

        public Criteria andAccresult2EqualTo(String value) {
            addCriterion("ACCRESULT2 =", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2NotEqualTo(String value) {
            addCriterion("ACCRESULT2 <>", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2GreaterThan(String value) {
            addCriterion("ACCRESULT2 >", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2GreaterThanOrEqualTo(String value) {
            addCriterion("ACCRESULT2 >=", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2LessThan(String value) {
            addCriterion("ACCRESULT2 <", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2LessThanOrEqualTo(String value) {
            addCriterion("ACCRESULT2 <=", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2Like(String value) {
            addCriterion("ACCRESULT2 like", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2NotLike(String value) {
            addCriterion("ACCRESULT2 not like", value, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2In(List<String> values) {
            addCriterion("ACCRESULT2 in", values, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2NotIn(List<String> values) {
            addCriterion("ACCRESULT2 not in", values, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2Between(String value1, String value2) {
            addCriterion("ACCRESULT2 between", value1, value2, "accresult2");
            return (Criteria) this;
        }

        public Criteria andAccresult2NotBetween(String value1, String value2) {
            addCriterion("ACCRESULT2 not between", value1, value2, "accresult2");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeIsNull() {
            addCriterion("HOSPITALCODE is null");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeIsNotNull() {
            addCriterion("HOSPITALCODE is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeEqualTo(String value) {
            addCriterion("HOSPITALCODE =", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeNotEqualTo(String value) {
            addCriterion("HOSPITALCODE <>", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeGreaterThan(String value) {
            addCriterion("HOSPITALCODE >", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeGreaterThanOrEqualTo(String value) {
            addCriterion("HOSPITALCODE >=", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeLessThan(String value) {
            addCriterion("HOSPITALCODE <", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeLessThanOrEqualTo(String value) {
            addCriterion("HOSPITALCODE <=", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeLike(String value) {
            addCriterion("HOSPITALCODE like", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeNotLike(String value) {
            addCriterion("HOSPITALCODE not like", value, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeIn(List<String> values) {
            addCriterion("HOSPITALCODE in", values, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeNotIn(List<String> values) {
            addCriterion("HOSPITALCODE not in", values, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeBetween(String value1, String value2) {
            addCriterion("HOSPITALCODE between", value1, value2, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalcodeNotBetween(String value1, String value2) {
            addCriterion("HOSPITALCODE not between", value1, value2, "hospitalcode");
            return (Criteria) this;
        }

        public Criteria andHospitalnameIsNull() {
            addCriterion("HOSPITALNAME is null");
            return (Criteria) this;
        }

        public Criteria andHospitalnameIsNotNull() {
            addCriterion("HOSPITALNAME is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalnameEqualTo(String value) {
            addCriterion("HOSPITALNAME =", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameNotEqualTo(String value) {
            addCriterion("HOSPITALNAME <>", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameGreaterThan(String value) {
            addCriterion("HOSPITALNAME >", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameGreaterThanOrEqualTo(String value) {
            addCriterion("HOSPITALNAME >=", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameLessThan(String value) {
            addCriterion("HOSPITALNAME <", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameLessThanOrEqualTo(String value) {
            addCriterion("HOSPITALNAME <=", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameLike(String value) {
            addCriterion("HOSPITALNAME like", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameNotLike(String value) {
            addCriterion("HOSPITALNAME not like", value, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameIn(List<String> values) {
            addCriterion("HOSPITALNAME in", values, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameNotIn(List<String> values) {
            addCriterion("HOSPITALNAME not in", values, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameBetween(String value1, String value2) {
            addCriterion("HOSPITALNAME between", value1, value2, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andHospitalnameNotBetween(String value1, String value2) {
            addCriterion("HOSPITALNAME not between", value1, value2, "hospitalname");
            return (Criteria) this;
        }

        public Criteria andClaimpayIsNull() {
            addCriterion("CLAIMPAY is null");
            return (Criteria) this;
        }

        public Criteria andClaimpayIsNotNull() {
            addCriterion("CLAIMPAY is not null");
            return (Criteria) this;
        }

        public Criteria andClaimpayEqualTo(BigDecimal value) {
            addCriterion("CLAIMPAY =", value, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayNotEqualTo(BigDecimal value) {
            addCriterion("CLAIMPAY <>", value, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayGreaterThan(BigDecimal value) {
            addCriterion("CLAIMPAY >", value, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CLAIMPAY >=", value, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayLessThan(BigDecimal value) {
            addCriterion("CLAIMPAY <", value, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CLAIMPAY <=", value, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayIn(List<BigDecimal> values) {
            addCriterion("CLAIMPAY in", values, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayNotIn(List<BigDecimal> values) {
            addCriterion("CLAIMPAY not in", values, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLAIMPAY between", value1, value2, "claimpay");
            return (Criteria) this;
        }

        public Criteria andClaimpayNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLAIMPAY not between", value1, value2, "claimpay");
            return (Criteria) this;
        }

        public Criteria andAccprovinceIsNull() {
            addCriterion("ACCPROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andAccprovinceIsNotNull() {
            addCriterion("ACCPROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andAccprovinceEqualTo(String value) {
            addCriterion("ACCPROVINCE =", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceNotEqualTo(String value) {
            addCriterion("ACCPROVINCE <>", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceGreaterThan(String value) {
            addCriterion("ACCPROVINCE >", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceGreaterThanOrEqualTo(String value) {
            addCriterion("ACCPROVINCE >=", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceLessThan(String value) {
            addCriterion("ACCPROVINCE <", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceLessThanOrEqualTo(String value) {
            addCriterion("ACCPROVINCE <=", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceLike(String value) {
            addCriterion("ACCPROVINCE like", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceNotLike(String value) {
            addCriterion("ACCPROVINCE not like", value, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceIn(List<String> values) {
            addCriterion("ACCPROVINCE in", values, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceNotIn(List<String> values) {
            addCriterion("ACCPROVINCE not in", values, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceBetween(String value1, String value2) {
            addCriterion("ACCPROVINCE between", value1, value2, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAccprovinceNotBetween(String value1, String value2) {
            addCriterion("ACCPROVINCE not between", value1, value2, "accprovince");
            return (Criteria) this;
        }

        public Criteria andAcccityIsNull() {
            addCriterion("ACCCITY is null");
            return (Criteria) this;
        }

        public Criteria andAcccityIsNotNull() {
            addCriterion("ACCCITY is not null");
            return (Criteria) this;
        }

        public Criteria andAcccityEqualTo(String value) {
            addCriterion("ACCCITY =", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityNotEqualTo(String value) {
            addCriterion("ACCCITY <>", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityGreaterThan(String value) {
            addCriterion("ACCCITY >", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityGreaterThanOrEqualTo(String value) {
            addCriterion("ACCCITY >=", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityLessThan(String value) {
            addCriterion("ACCCITY <", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityLessThanOrEqualTo(String value) {
            addCriterion("ACCCITY <=", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityLike(String value) {
            addCriterion("ACCCITY like", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityNotLike(String value) {
            addCriterion("ACCCITY not like", value, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityIn(List<String> values) {
            addCriterion("ACCCITY in", values, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityNotIn(List<String> values) {
            addCriterion("ACCCITY not in", values, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityBetween(String value1, String value2) {
            addCriterion("ACCCITY between", value1, value2, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccityNotBetween(String value1, String value2) {
            addCriterion("ACCCITY not between", value1, value2, "acccity");
            return (Criteria) this;
        }

        public Criteria andAcccountyIsNull() {
            addCriterion("ACCCOUNTY is null");
            return (Criteria) this;
        }

        public Criteria andAcccountyIsNotNull() {
            addCriterion("ACCCOUNTY is not null");
            return (Criteria) this;
        }

        public Criteria andAcccountyEqualTo(String value) {
            addCriterion("ACCCOUNTY =", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyNotEqualTo(String value) {
            addCriterion("ACCCOUNTY <>", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyGreaterThan(String value) {
            addCriterion("ACCCOUNTY >", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyGreaterThanOrEqualTo(String value) {
            addCriterion("ACCCOUNTY >=", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyLessThan(String value) {
            addCriterion("ACCCOUNTY <", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyLessThanOrEqualTo(String value) {
            addCriterion("ACCCOUNTY <=", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyLike(String value) {
            addCriterion("ACCCOUNTY like", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyNotLike(String value) {
            addCriterion("ACCCOUNTY not like", value, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyIn(List<String> values) {
            addCriterion("ACCCOUNTY in", values, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyNotIn(List<String> values) {
            addCriterion("ACCCOUNTY not in", values, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyBetween(String value1, String value2) {
            addCriterion("ACCCOUNTY between", value1, value2, "acccounty");
            return (Criteria) this;
        }

        public Criteria andAcccountyNotBetween(String value1, String value2) {
            addCriterion("ACCCOUNTY not between", value1, value2, "acccounty");
            return (Criteria) this;
        }

        public Criteria andComcodeIsNull() {
            addCriterion("COMCODE is null");
            return (Criteria) this;
        }

        public Criteria andComcodeIsNotNull() {
            addCriterion("COMCODE is not null");
            return (Criteria) this;
        }

        public Criteria andComcodeEqualTo(String value) {
            addCriterion("COMCODE =", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeNotEqualTo(String value) {
            addCriterion("COMCODE <>", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeGreaterThan(String value) {
            addCriterion("COMCODE >", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeGreaterThanOrEqualTo(String value) {
            addCriterion("COMCODE >=", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeLessThan(String value) {
            addCriterion("COMCODE <", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeLessThanOrEqualTo(String value) {
            addCriterion("COMCODE <=", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeLike(String value) {
            addCriterion("COMCODE like", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeNotLike(String value) {
            addCriterion("COMCODE not like", value, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeIn(List<String> values) {
            addCriterion("COMCODE in", values, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeNotIn(List<String> values) {
            addCriterion("COMCODE not in", values, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeBetween(String value1, String value2) {
            addCriterion("COMCODE between", value1, value2, "comcode");
            return (Criteria) this;
        }

        public Criteria andComcodeNotBetween(String value1, String value2) {
            addCriterion("COMCODE not between", value1, value2, "comcode");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorIsNull() {
            addCriterion("MODIFYOPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorIsNotNull() {
            addCriterion("MODIFYOPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorEqualTo(String value) {
            addCriterion("MODIFYOPERATOR =", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorNotEqualTo(String value) {
            addCriterion("MODIFYOPERATOR <>", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorGreaterThan(String value) {
            addCriterion("MODIFYOPERATOR >", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYOPERATOR >=", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorLessThan(String value) {
            addCriterion("MODIFYOPERATOR <", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorLessThanOrEqualTo(String value) {
            addCriterion("MODIFYOPERATOR <=", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorLike(String value) {
            addCriterion("MODIFYOPERATOR like", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorNotLike(String value) {
            addCriterion("MODIFYOPERATOR not like", value, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorIn(List<String> values) {
            addCriterion("MODIFYOPERATOR in", values, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorNotIn(List<String> values) {
            addCriterion("MODIFYOPERATOR not in", values, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorBetween(String value1, String value2) {
            addCriterion("MODIFYOPERATOR between", value1, value2, "modifyoperator");
            return (Criteria) this;
        }

        public Criteria andModifyoperatorNotBetween(String value1, String value2) {
            addCriterion("MODIFYOPERATOR not between", value1, value2, "modifyoperator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table llaccident
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 14 20:16:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table llaccident
     *
     * @mbg.generated Fri Dec 14 20:16:57 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}