package com.guobao.dto.lis;

import java.math.BigDecimal;
import java.util.Date;

public class LaCom_Lis extends LaCom_LisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.ManageCom
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String managecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.AreaType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String areatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.AgentcyType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String agentcytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.BankType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String banktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Name
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.UpAgentCom
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String upagentcom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.UpAgentName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String upagentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.GetUpFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String getupflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.RegionCode
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String regioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.T3Code
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String t3code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.T3Name
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String t3name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.BranchARea
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String brancharea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.LinkMan
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Founddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date founddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.State
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Canceldate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date canceldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.CancelReason
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String cancelreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Birthday
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.BankName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.AccountNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String accountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.ReceivName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String receivname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Country
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Province
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.City
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Address
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.ZipCode
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Telephone1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String telephone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Telephone2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String telephone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.MobilePhone
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Fax
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.EMail1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String email1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.EMail2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String email2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.CertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String certifino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.CommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String commitflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Startdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Enddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Circtype
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String circtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.CheckFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String checkflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.PCertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String pcertifino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.PCommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String pcommitflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.PStartdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date pstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.PEnddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date penddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.YCertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String ycertifino;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.YCommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String ycommitflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.YStartdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date ystartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.YEnddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date yenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.YCheckFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String ycheckflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.upcom1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String upcom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.upcom2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String upcom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.upcom3
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String upcom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.com
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String com;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.IDNoType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String idnotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.IDNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Sex
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.NativePlace
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String nativeplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Marriage
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String marriage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Degree
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Speciality
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String speciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Noti
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String noti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Launchdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date launchdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.TMRAgentGrade
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String tmragentgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Insuredate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date insuredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Operator
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Makedate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.MakeTime
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.Modifydate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.ModifyTime
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date p1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Date p2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P3
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String p3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P4
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String p4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P5
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String p5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P6
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Long p6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P7
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private Long p7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P8
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private BigDecimal p8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P9
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private BigDecimal p9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.P10
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private BigDecimal p10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lacom.channeltype
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    private String channeltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.ManageCom
     *
     * @return the value of lacom.ManageCom
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getManagecom() {
        return managecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.ManageCom
     *
     * @param managecom the value for lacom.ManageCom
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setManagecom(String managecom) {
        this.managecom = managecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.AreaType
     *
     * @return the value of lacom.AreaType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getAreatype() {
        return areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.AreaType
     *
     * @param areatype the value for lacom.AreaType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setAreatype(String areatype) {
        this.areatype = areatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.AgentcyType
     *
     * @return the value of lacom.AgentcyType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getAgentcytype() {
        return agentcytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.AgentcyType
     *
     * @param agentcytype the value for lacom.AgentcyType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setAgentcytype(String agentcytype) {
        this.agentcytype = agentcytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.BankType
     *
     * @return the value of lacom.BankType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getBanktype() {
        return banktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.BankType
     *
     * @param banktype the value for lacom.BankType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setBanktype(String banktype) {
        this.banktype = banktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Name
     *
     * @return the value of lacom.Name
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Name
     *
     * @param name the value for lacom.Name
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.UpAgentCom
     *
     * @return the value of lacom.UpAgentCom
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getUpagentcom() {
        return upagentcom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.UpAgentCom
     *
     * @param upagentcom the value for lacom.UpAgentCom
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setUpagentcom(String upagentcom) {
        this.upagentcom = upagentcom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.UpAgentName
     *
     * @return the value of lacom.UpAgentName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getUpagentname() {
        return upagentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.UpAgentName
     *
     * @param upagentname the value for lacom.UpAgentName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setUpagentname(String upagentname) {
        this.upagentname = upagentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.GetUpFlag
     *
     * @return the value of lacom.GetUpFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getGetupflag() {
        return getupflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.GetUpFlag
     *
     * @param getupflag the value for lacom.GetUpFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setGetupflag(String getupflag) {
        this.getupflag = getupflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.RegionCode
     *
     * @return the value of lacom.RegionCode
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getRegioncode() {
        return regioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.RegionCode
     *
     * @param regioncode the value for lacom.RegionCode
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.T3Code
     *
     * @return the value of lacom.T3Code
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getT3code() {
        return t3code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.T3Code
     *
     * @param t3code the value for lacom.T3Code
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setT3code(String t3code) {
        this.t3code = t3code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.T3Name
     *
     * @return the value of lacom.T3Name
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getT3name() {
        return t3name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.T3Name
     *
     * @param t3name the value for lacom.T3Name
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setT3name(String t3name) {
        this.t3name = t3name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.BranchARea
     *
     * @return the value of lacom.BranchARea
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getBrancharea() {
        return brancharea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.BranchARea
     *
     * @param brancharea the value for lacom.BranchARea
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setBrancharea(String brancharea) {
        this.brancharea = brancharea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.LinkMan
     *
     * @return the value of lacom.LinkMan
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.LinkMan
     *
     * @param linkman the value for lacom.LinkMan
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Founddate
     *
     * @return the value of lacom.Founddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getFounddate() {
        return founddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Founddate
     *
     * @param founddate the value for lacom.Founddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setFounddate(Date founddate) {
        this.founddate = founddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.State
     *
     * @return the value of lacom.State
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.State
     *
     * @param state the value for lacom.State
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Canceldate
     *
     * @return the value of lacom.Canceldate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getCanceldate() {
        return canceldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Canceldate
     *
     * @param canceldate the value for lacom.Canceldate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCanceldate(Date canceldate) {
        this.canceldate = canceldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.CancelReason
     *
     * @return the value of lacom.CancelReason
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCancelreason() {
        return cancelreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.CancelReason
     *
     * @param cancelreason the value for lacom.CancelReason
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCancelreason(String cancelreason) {
        this.cancelreason = cancelreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Birthday
     *
     * @return the value of lacom.Birthday
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Birthday
     *
     * @param birthday the value for lacom.Birthday
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.BankName
     *
     * @return the value of lacom.BankName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.BankName
     *
     * @param bankname the value for lacom.BankName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.AccountNo
     *
     * @return the value of lacom.AccountNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.AccountNo
     *
     * @param accountno the value for lacom.AccountNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.ReceivName
     *
     * @return the value of lacom.ReceivName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getReceivname() {
        return receivname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.ReceivName
     *
     * @param receivname the value for lacom.ReceivName
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setReceivname(String receivname) {
        this.receivname = receivname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Country
     *
     * @return the value of lacom.Country
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Country
     *
     * @param country the value for lacom.Country
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Province
     *
     * @return the value of lacom.Province
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Province
     *
     * @param province the value for lacom.Province
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.City
     *
     * @return the value of lacom.City
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.City
     *
     * @param city the value for lacom.City
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Address
     *
     * @return the value of lacom.Address
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Address
     *
     * @param address the value for lacom.Address
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.ZipCode
     *
     * @return the value of lacom.ZipCode
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.ZipCode
     *
     * @param zipcode the value for lacom.ZipCode
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Telephone1
     *
     * @return the value of lacom.Telephone1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getTelephone1() {
        return telephone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Telephone1
     *
     * @param telephone1 the value for lacom.Telephone1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setTelephone1(String telephone1) {
        this.telephone1 = telephone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Telephone2
     *
     * @return the value of lacom.Telephone2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getTelephone2() {
        return telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Telephone2
     *
     * @param telephone2 the value for lacom.Telephone2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.MobilePhone
     *
     * @return the value of lacom.MobilePhone
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.MobilePhone
     *
     * @param mobilephone the value for lacom.MobilePhone
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Fax
     *
     * @return the value of lacom.Fax
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Fax
     *
     * @param fax the value for lacom.Fax
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.EMail1
     *
     * @return the value of lacom.EMail1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.EMail1
     *
     * @param email1 the value for lacom.EMail1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.EMail2
     *
     * @return the value of lacom.EMail2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.EMail2
     *
     * @param email2 the value for lacom.EMail2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.CertifiNo
     *
     * @return the value of lacom.CertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCertifino() {
        return certifino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.CertifiNo
     *
     * @param certifino the value for lacom.CertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCertifino(String certifino) {
        this.certifino = certifino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.CommitFlag
     *
     * @return the value of lacom.CommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCommitflag() {
        return commitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.CommitFlag
     *
     * @param commitflag the value for lacom.CommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCommitflag(String commitflag) {
        this.commitflag = commitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Startdate
     *
     * @return the value of lacom.Startdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Startdate
     *
     * @param startdate the value for lacom.Startdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Enddate
     *
     * @return the value of lacom.Enddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Enddate
     *
     * @param enddate the value for lacom.Enddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Circtype
     *
     * @return the value of lacom.Circtype
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCirctype() {
        return circtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Circtype
     *
     * @param circtype the value for lacom.Circtype
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCirctype(String circtype) {
        this.circtype = circtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.CheckFlag
     *
     * @return the value of lacom.CheckFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCheckflag() {
        return checkflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.CheckFlag
     *
     * @param checkflag the value for lacom.CheckFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCheckflag(String checkflag) {
        this.checkflag = checkflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.PCertifiNo
     *
     * @return the value of lacom.PCertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getPcertifino() {
        return pcertifino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.PCertifiNo
     *
     * @param pcertifino the value for lacom.PCertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setPcertifino(String pcertifino) {
        this.pcertifino = pcertifino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.PCommitFlag
     *
     * @return the value of lacom.PCommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getPcommitflag() {
        return pcommitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.PCommitFlag
     *
     * @param pcommitflag the value for lacom.PCommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setPcommitflag(String pcommitflag) {
        this.pcommitflag = pcommitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.PStartdate
     *
     * @return the value of lacom.PStartdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getPstartdate() {
        return pstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.PStartdate
     *
     * @param pstartdate the value for lacom.PStartdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setPstartdate(Date pstartdate) {
        this.pstartdate = pstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.PEnddate
     *
     * @return the value of lacom.PEnddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getPenddate() {
        return penddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.PEnddate
     *
     * @param penddate the value for lacom.PEnddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setPenddate(Date penddate) {
        this.penddate = penddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.YCertifiNo
     *
     * @return the value of lacom.YCertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getYcertifino() {
        return ycertifino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.YCertifiNo
     *
     * @param ycertifino the value for lacom.YCertifiNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setYcertifino(String ycertifino) {
        this.ycertifino = ycertifino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.YCommitFlag
     *
     * @return the value of lacom.YCommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getYcommitflag() {
        return ycommitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.YCommitFlag
     *
     * @param ycommitflag the value for lacom.YCommitFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setYcommitflag(String ycommitflag) {
        this.ycommitflag = ycommitflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.YStartdate
     *
     * @return the value of lacom.YStartdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getYstartdate() {
        return ystartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.YStartdate
     *
     * @param ystartdate the value for lacom.YStartdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setYstartdate(Date ystartdate) {
        this.ystartdate = ystartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.YEnddate
     *
     * @return the value of lacom.YEnddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getYenddate() {
        return yenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.YEnddate
     *
     * @param yenddate the value for lacom.YEnddate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setYenddate(Date yenddate) {
        this.yenddate = yenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.YCheckFlag
     *
     * @return the value of lacom.YCheckFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getYcheckflag() {
        return ycheckflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.YCheckFlag
     *
     * @param ycheckflag the value for lacom.YCheckFlag
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setYcheckflag(String ycheckflag) {
        this.ycheckflag = ycheckflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.upcom1
     *
     * @return the value of lacom.upcom1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getUpcom1() {
        return upcom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.upcom1
     *
     * @param upcom1 the value for lacom.upcom1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setUpcom1(String upcom1) {
        this.upcom1 = upcom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.upcom2
     *
     * @return the value of lacom.upcom2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getUpcom2() {
        return upcom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.upcom2
     *
     * @param upcom2 the value for lacom.upcom2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setUpcom2(String upcom2) {
        this.upcom2 = upcom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.upcom3
     *
     * @return the value of lacom.upcom3
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getUpcom3() {
        return upcom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.upcom3
     *
     * @param upcom3 the value for lacom.upcom3
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setUpcom3(String upcom3) {
        this.upcom3 = upcom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.com
     *
     * @return the value of lacom.com
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getCom() {
        return com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.com
     *
     * @param com the value for lacom.com
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setCom(String com) {
        this.com = com;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.IDNoType
     *
     * @return the value of lacom.IDNoType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getIdnotype() {
        return idnotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.IDNoType
     *
     * @param idnotype the value for lacom.IDNoType
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setIdnotype(String idnotype) {
        this.idnotype = idnotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.IDNo
     *
     * @return the value of lacom.IDNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.IDNo
     *
     * @param idno the value for lacom.IDNo
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Sex
     *
     * @return the value of lacom.Sex
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Sex
     *
     * @param sex the value for lacom.Sex
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.NativePlace
     *
     * @return the value of lacom.NativePlace
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.NativePlace
     *
     * @param nativeplace the value for lacom.NativePlace
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Marriage
     *
     * @return the value of lacom.Marriage
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Marriage
     *
     * @param marriage the value for lacom.Marriage
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Degree
     *
     * @return the value of lacom.Degree
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Degree
     *
     * @param degree the value for lacom.Degree
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Speciality
     *
     * @return the value of lacom.Speciality
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Speciality
     *
     * @param speciality the value for lacom.Speciality
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Noti
     *
     * @return the value of lacom.Noti
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getNoti() {
        return noti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Noti
     *
     * @param noti the value for lacom.Noti
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setNoti(String noti) {
        this.noti = noti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Launchdate
     *
     * @return the value of lacom.Launchdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getLaunchdate() {
        return launchdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Launchdate
     *
     * @param launchdate the value for lacom.Launchdate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setLaunchdate(Date launchdate) {
        this.launchdate = launchdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.TMRAgentGrade
     *
     * @return the value of lacom.TMRAgentGrade
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getTmragentgrade() {
        return tmragentgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.TMRAgentGrade
     *
     * @param tmragentgrade the value for lacom.TMRAgentGrade
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setTmragentgrade(String tmragentgrade) {
        this.tmragentgrade = tmragentgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Insuredate
     *
     * @return the value of lacom.Insuredate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getInsuredate() {
        return insuredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Insuredate
     *
     * @param insuredate the value for lacom.Insuredate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setInsuredate(Date insuredate) {
        this.insuredate = insuredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Operator
     *
     * @return the value of lacom.Operator
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Operator
     *
     * @param operator the value for lacom.Operator
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Makedate
     *
     * @return the value of lacom.Makedate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Makedate
     *
     * @param makedate the value for lacom.Makedate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.MakeTime
     *
     * @return the value of lacom.MakeTime
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.MakeTime
     *
     * @param maketime the value for lacom.MakeTime
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setMaketime(String maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.Modifydate
     *
     * @return the value of lacom.Modifydate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.Modifydate
     *
     * @param modifydate the value for lacom.Modifydate
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.ModifyTime
     *
     * @return the value of lacom.ModifyTime
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.ModifyTime
     *
     * @param modifytime the value for lacom.ModifyTime
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P1
     *
     * @return the value of lacom.P1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getP1() {
        return p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P1
     *
     * @param p1 the value for lacom.P1
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP1(Date p1) {
        this.p1 = p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P2
     *
     * @return the value of lacom.P2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Date getP2() {
        return p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P2
     *
     * @param p2 the value for lacom.P2
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP2(Date p2) {
        this.p2 = p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P3
     *
     * @return the value of lacom.P3
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getP3() {
        return p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P3
     *
     * @param p3 the value for lacom.P3
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP3(String p3) {
        this.p3 = p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P4
     *
     * @return the value of lacom.P4
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getP4() {
        return p4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P4
     *
     * @param p4 the value for lacom.P4
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP4(String p4) {
        this.p4 = p4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P5
     *
     * @return the value of lacom.P5
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getP5() {
        return p5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P5
     *
     * @param p5 the value for lacom.P5
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP5(String p5) {
        this.p5 = p5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P6
     *
     * @return the value of lacom.P6
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Long getP6() {
        return p6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P6
     *
     * @param p6 the value for lacom.P6
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP6(Long p6) {
        this.p6 = p6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P7
     *
     * @return the value of lacom.P7
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public Long getP7() {
        return p7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P7
     *
     * @param p7 the value for lacom.P7
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP7(Long p7) {
        this.p7 = p7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P8
     *
     * @return the value of lacom.P8
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public BigDecimal getP8() {
        return p8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P8
     *
     * @param p8 the value for lacom.P8
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP8(BigDecimal p8) {
        this.p8 = p8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P9
     *
     * @return the value of lacom.P9
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public BigDecimal getP9() {
        return p9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P9
     *
     * @param p9 the value for lacom.P9
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP9(BigDecimal p9) {
        this.p9 = p9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.P10
     *
     * @return the value of lacom.P10
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public BigDecimal getP10() {
        return p10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.P10
     *
     * @param p10 the value for lacom.P10
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setP10(BigDecimal p10) {
        this.p10 = p10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lacom.channeltype
     *
     * @return the value of lacom.channeltype
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public String getChanneltype() {
        return channeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lacom.channeltype
     *
     * @param channeltype the value for lacom.channeltype
     *
     * @mbggenerated Mon May 07 20:23:32 CST 2018
     */
    public void setChanneltype(String channeltype) {
        this.channeltype = channeltype;
    }
}