package com.guobao.dto.lis;

import java.math.BigDecimal;
import java.util.Date;

public class LcBnf_Lis extends LcBnf_LisKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ContNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String contno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.RelationToInsured
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String relationtoinsured;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.BnfLot
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private BigDecimal bnflot;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.CustomerNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String customerno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Name
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Sex
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Birthday
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.IDType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String idtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.IDNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String idno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Operator
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.MakeDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private Date makedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.MakeTime
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String maketime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ModifyDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private Date modifydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ModifyTime
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String modifytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.PostalAddress
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String postaladdress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ZipCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String zipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.BankCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String bankcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.BankAccNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String bankaccno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.AccName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String accname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.IDExpDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private Date idexpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Mobile
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ManageCom
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String managecom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ComCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String comcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ModifyOperator
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String modifyoperator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.NativePlace
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String nativeplace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.MarRiage
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String marriage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.OccupationType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String occupationtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.OccupationCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String occupationcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.WorkType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String worktype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.PluralityType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String pluralitytype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.LicenseType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String licensetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.LastName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String lastname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.FirstName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String firstname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.LastNameEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String lastnameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.FirstNameEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String firstnameen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.NanmEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String nanmen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Language
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Email
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Phone
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.IsCity
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String iscity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.AddressNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String addressno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.BankProvince
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String bankprovince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.IsLongValid
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String islongvalid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.IsSocialInsuFlag
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String issocialinsuflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ResidentsType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String residentstype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.WorkCompName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String workcompname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.Ismotorcyclelicense
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String ismotorcyclelicense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.update_time
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lcbnf.ISLegal
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	private String islegal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ContNo
	 * @return  the value of lcbnf.ContNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getContno() {
		return contno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ContNo
	 * @param contno  the value for lcbnf.ContNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setContno(String contno) {
		this.contno = contno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.RelationToInsured
	 * @return  the value of lcbnf.RelationToInsured
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getRelationtoinsured() {
		return relationtoinsured;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.RelationToInsured
	 * @param relationtoinsured  the value for lcbnf.RelationToInsured
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setRelationtoinsured(String relationtoinsured) {
		this.relationtoinsured = relationtoinsured;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.BnfLot
	 * @return  the value of lcbnf.BnfLot
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public BigDecimal getBnflot() {
		return bnflot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.BnfLot
	 * @param bnflot  the value for lcbnf.BnfLot
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setBnflot(BigDecimal bnflot) {
		this.bnflot = bnflot;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.CustomerNo
	 * @return  the value of lcbnf.CustomerNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getCustomerno() {
		return customerno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.CustomerNo
	 * @param customerno  the value for lcbnf.CustomerNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setCustomerno(String customerno) {
		this.customerno = customerno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Name
	 * @return  the value of lcbnf.Name
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Name
	 * @param name  the value for lcbnf.Name
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Sex
	 * @return  the value of lcbnf.Sex
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Sex
	 * @param sex  the value for lcbnf.Sex
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Birthday
	 * @return  the value of lcbnf.Birthday
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Birthday
	 * @param birthday  the value for lcbnf.Birthday
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.IDType
	 * @return  the value of lcbnf.IDType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIdtype() {
		return idtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.IDType
	 * @param idtype  the value for lcbnf.IDType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIdtype(String idtype) {
		this.idtype = idtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.IDNo
	 * @return  the value of lcbnf.IDNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.IDNo
	 * @param idno  the value for lcbnf.IDNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Operator
	 * @return  the value of lcbnf.Operator
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Operator
	 * @param operator  the value for lcbnf.Operator
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.MakeDate
	 * @return  the value of lcbnf.MakeDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public Date getMakedate() {
		return makedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.MakeDate
	 * @param makedate  the value for lcbnf.MakeDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setMakedate(Date makedate) {
		this.makedate = makedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.MakeTime
	 * @return  the value of lcbnf.MakeTime
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getMaketime() {
		return maketime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.MakeTime
	 * @param maketime  the value for lcbnf.MakeTime
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setMaketime(String maketime) {
		this.maketime = maketime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ModifyDate
	 * @return  the value of lcbnf.ModifyDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ModifyDate
	 * @param modifydate  the value for lcbnf.ModifyDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ModifyTime
	 * @return  the value of lcbnf.ModifyTime
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ModifyTime
	 * @param modifytime  the value for lcbnf.ModifyTime
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setModifytime(String modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.PostalAddress
	 * @return  the value of lcbnf.PostalAddress
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getPostaladdress() {
		return postaladdress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.PostalAddress
	 * @param postaladdress  the value for lcbnf.PostalAddress
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setPostaladdress(String postaladdress) {
		this.postaladdress = postaladdress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ZipCode
	 * @return  the value of lcbnf.ZipCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ZipCode
	 * @param zipcode  the value for lcbnf.ZipCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.BankCode
	 * @return  the value of lcbnf.BankCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getBankcode() {
		return bankcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.BankCode
	 * @param bankcode  the value for lcbnf.BankCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.BankAccNo
	 * @return  the value of lcbnf.BankAccNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getBankaccno() {
		return bankaccno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.BankAccNo
	 * @param bankaccno  the value for lcbnf.BankAccNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setBankaccno(String bankaccno) {
		this.bankaccno = bankaccno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.AccName
	 * @return  the value of lcbnf.AccName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getAccname() {
		return accname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.AccName
	 * @param accname  the value for lcbnf.AccName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setAccname(String accname) {
		this.accname = accname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.IDExpDate
	 * @return  the value of lcbnf.IDExpDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public Date getIdexpdate() {
		return idexpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.IDExpDate
	 * @param idexpdate  the value for lcbnf.IDExpDate
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIdexpdate(Date idexpdate) {
		this.idexpdate = idexpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Mobile
	 * @return  the value of lcbnf.Mobile
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Mobile
	 * @param mobile  the value for lcbnf.Mobile
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ManageCom
	 * @return  the value of lcbnf.ManageCom
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getManagecom() {
		return managecom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ManageCom
	 * @param managecom  the value for lcbnf.ManageCom
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setManagecom(String managecom) {
		this.managecom = managecom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ComCode
	 * @return  the value of lcbnf.ComCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getComcode() {
		return comcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ComCode
	 * @param comcode  the value for lcbnf.ComCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setComcode(String comcode) {
		this.comcode = comcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ModifyOperator
	 * @return  the value of lcbnf.ModifyOperator
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getModifyoperator() {
		return modifyoperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ModifyOperator
	 * @param modifyoperator  the value for lcbnf.ModifyOperator
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setModifyoperator(String modifyoperator) {
		this.modifyoperator = modifyoperator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.NativePlace
	 * @return  the value of lcbnf.NativePlace
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getNativeplace() {
		return nativeplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.NativePlace
	 * @param nativeplace  the value for lcbnf.NativePlace
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setNativeplace(String nativeplace) {
		this.nativeplace = nativeplace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.MarRiage
	 * @return  the value of lcbnf.MarRiage
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getMarriage() {
		return marriage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.MarRiage
	 * @param marriage  the value for lcbnf.MarRiage
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setMarriage(String marriage) {
		this.marriage = marriage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.OccupationType
	 * @return  the value of lcbnf.OccupationType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getOccupationtype() {
		return occupationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.OccupationType
	 * @param occupationtype  the value for lcbnf.OccupationType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setOccupationtype(String occupationtype) {
		this.occupationtype = occupationtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.OccupationCode
	 * @return  the value of lcbnf.OccupationCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getOccupationcode() {
		return occupationcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.OccupationCode
	 * @param occupationcode  the value for lcbnf.OccupationCode
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setOccupationcode(String occupationcode) {
		this.occupationcode = occupationcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.WorkType
	 * @return  the value of lcbnf.WorkType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getWorktype() {
		return worktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.WorkType
	 * @param worktype  the value for lcbnf.WorkType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setWorktype(String worktype) {
		this.worktype = worktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.PluralityType
	 * @return  the value of lcbnf.PluralityType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getPluralitytype() {
		return pluralitytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.PluralityType
	 * @param pluralitytype  the value for lcbnf.PluralityType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setPluralitytype(String pluralitytype) {
		this.pluralitytype = pluralitytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.LicenseType
	 * @return  the value of lcbnf.LicenseType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getLicensetype() {
		return licensetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.LicenseType
	 * @param licensetype  the value for lcbnf.LicenseType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setLicensetype(String licensetype) {
		this.licensetype = licensetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.LastName
	 * @return  the value of lcbnf.LastName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getLastname() {
		return lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.LastName
	 * @param lastname  the value for lcbnf.LastName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.FirstName
	 * @return  the value of lcbnf.FirstName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.FirstName
	 * @param firstname  the value for lcbnf.FirstName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.LastNameEn
	 * @return  the value of lcbnf.LastNameEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getLastnameen() {
		return lastnameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.LastNameEn
	 * @param lastnameen  the value for lcbnf.LastNameEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setLastnameen(String lastnameen) {
		this.lastnameen = lastnameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.FirstNameEn
	 * @return  the value of lcbnf.FirstNameEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getFirstnameen() {
		return firstnameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.FirstNameEn
	 * @param firstnameen  the value for lcbnf.FirstNameEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setFirstnameen(String firstnameen) {
		this.firstnameen = firstnameen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.NanmEn
	 * @return  the value of lcbnf.NanmEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getNanmen() {
		return nanmen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.NanmEn
	 * @param nanmen  the value for lcbnf.NanmEn
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setNanmen(String nanmen) {
		this.nanmen = nanmen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Language
	 * @return  the value of lcbnf.Language
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Language
	 * @param language  the value for lcbnf.Language
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Email
	 * @return  the value of lcbnf.Email
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Email
	 * @param email  the value for lcbnf.Email
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Phone
	 * @return  the value of lcbnf.Phone
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Phone
	 * @param phone  the value for lcbnf.Phone
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.IsCity
	 * @return  the value of lcbnf.IsCity
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIscity() {
		return iscity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.IsCity
	 * @param iscity  the value for lcbnf.IsCity
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIscity(String iscity) {
		this.iscity = iscity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.AddressNo
	 * @return  the value of lcbnf.AddressNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getAddressno() {
		return addressno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.AddressNo
	 * @param addressno  the value for lcbnf.AddressNo
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setAddressno(String addressno) {
		this.addressno = addressno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.BankProvince
	 * @return  the value of lcbnf.BankProvince
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getBankprovince() {
		return bankprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.BankProvince
	 * @param bankprovince  the value for lcbnf.BankProvince
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setBankprovince(String bankprovince) {
		this.bankprovince = bankprovince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.IsLongValid
	 * @return  the value of lcbnf.IsLongValid
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIslongvalid() {
		return islongvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.IsLongValid
	 * @param islongvalid  the value for lcbnf.IsLongValid
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIslongvalid(String islongvalid) {
		this.islongvalid = islongvalid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.IsSocialInsuFlag
	 * @return  the value of lcbnf.IsSocialInsuFlag
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIssocialinsuflag() {
		return issocialinsuflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.IsSocialInsuFlag
	 * @param issocialinsuflag  the value for lcbnf.IsSocialInsuFlag
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIssocialinsuflag(String issocialinsuflag) {
		this.issocialinsuflag = issocialinsuflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ResidentsType
	 * @return  the value of lcbnf.ResidentsType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getResidentstype() {
		return residentstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ResidentsType
	 * @param residentstype  the value for lcbnf.ResidentsType
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setResidentstype(String residentstype) {
		this.residentstype = residentstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.WorkCompName
	 * @return  the value of lcbnf.WorkCompName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getWorkcompname() {
		return workcompname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.WorkCompName
	 * @param workcompname  the value for lcbnf.WorkCompName
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setWorkcompname(String workcompname) {
		this.workcompname = workcompname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.Ismotorcyclelicense
	 * @return  the value of lcbnf.Ismotorcyclelicense
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIsmotorcyclelicense() {
		return ismotorcyclelicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.Ismotorcyclelicense
	 * @param ismotorcyclelicense  the value for lcbnf.Ismotorcyclelicense
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIsmotorcyclelicense(String ismotorcyclelicense) {
		this.ismotorcyclelicense = ismotorcyclelicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.update_time
	 * @return  the value of lcbnf.update_time
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.update_time
	 * @param updateTime  the value for lcbnf.update_time
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lcbnf.ISLegal
	 * @return  the value of lcbnf.ISLegal
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public String getIslegal() {
		return islegal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lcbnf.ISLegal
	 * @param islegal  the value for lcbnf.ISLegal
	 * @mbggenerated  Thu Jun 07 17:14:38 CST 2018
	 */
	public void setIslegal(String islegal) {
		this.islegal = islegal;
	}
}