package com.guobao.dto.lis;

public class LcCont_LisWithBLOBs extends LcCont_Lis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccont.REMARK
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccont.FORCEUWREASON
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String forceuwreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccont.DELAYREASONDESC
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String delayreasondesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccont.REMARK
     *
     * @return the value of lccont.REMARK
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccont.REMARK
     *
     * @param remark the value for lccont.REMARK
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccont.FORCEUWREASON
     *
     * @return the value of lccont.FORCEUWREASON
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getForceuwreason() {
        return forceuwreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccont.FORCEUWREASON
     *
     * @param forceuwreason the value for lccont.FORCEUWREASON
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setForceuwreason(String forceuwreason) {
        this.forceuwreason = forceuwreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccont.DELAYREASONDESC
     *
     * @return the value of lccont.DELAYREASONDESC
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getDelayreasondesc() {
        return delayreasondesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccont.DELAYREASONDESC
     *
     * @param delayreasondesc the value for lccont.DELAYREASONDESC
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setDelayreasondesc(String delayreasondesc) {
        this.delayreasondesc = delayreasondesc;
    }
}