package com.guobao.dto.lis;

public class LcConThangUpState_LisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.CONTNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String contno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.HANGUPTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String hanguptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.INSUREDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String insuredno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.POLNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String polno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.CONTNO
     *
     * @return the value of lcconthangupstate.CONTNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getContno() {
        return contno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.CONTNO
     *
     * @param contno the value for lcconthangupstate.CONTNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setContno(String contno) {
        this.contno = contno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.HANGUPTYPE
     *
     * @return the value of lcconthangupstate.HANGUPTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getHanguptype() {
        return hanguptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.HANGUPTYPE
     *
     * @param hanguptype the value for lcconthangupstate.HANGUPTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setHanguptype(String hanguptype) {
        this.hanguptype = hanguptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.INSUREDNO
     *
     * @return the value of lcconthangupstate.INSUREDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getInsuredno() {
        return insuredno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.INSUREDNO
     *
     * @param insuredno the value for lcconthangupstate.INSUREDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setInsuredno(String insuredno) {
        this.insuredno = insuredno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.POLNO
     *
     * @return the value of lcconthangupstate.POLNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPolno() {
        return polno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.POLNO
     *
     * @param polno the value for lcconthangupstate.POLNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPolno(String polno) {
        this.polno = polno;
    }
}