package com.guobao.dto.lis;

import java.util.Date;

public class LcContState_Lis extends LcContState_LisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.STATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.STATEREASON
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String statereason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.ENDDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.REMARK
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.OPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.MAKEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.MAKETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.MODIFYDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lccontstate.MODIFYTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.STATE
     *
     * @return the value of lccontstate.STATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.STATE
     *
     * @param state the value for lccontstate.STATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.STATEREASON
     *
     * @return the value of lccontstate.STATEREASON
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getStatereason() {
        return statereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.STATEREASON
     *
     * @param statereason the value for lccontstate.STATEREASON
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setStatereason(String statereason) {
        this.statereason = statereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.ENDDATE
     *
     * @return the value of lccontstate.ENDDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.ENDDATE
     *
     * @param enddate the value for lccontstate.ENDDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.REMARK
     *
     * @return the value of lccontstate.REMARK
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.REMARK
     *
     * @param remark the value for lccontstate.REMARK
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.OPERATOR
     *
     * @return the value of lccontstate.OPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.OPERATOR
     *
     * @param operator the value for lccontstate.OPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.MAKEDATE
     *
     * @return the value of lccontstate.MAKEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.MAKEDATE
     *
     * @param makedate the value for lccontstate.MAKEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.MAKETIME
     *
     * @return the value of lccontstate.MAKETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.MAKETIME
     *
     * @param maketime the value for lccontstate.MAKETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setMaketime(String maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.MODIFYDATE
     *
     * @return the value of lccontstate.MODIFYDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.MODIFYDATE
     *
     * @param modifydate the value for lccontstate.MODIFYDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lccontstate.MODIFYTIME
     *
     * @return the value of lccontstate.MODIFYTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lccontstate.MODIFYTIME
     *
     * @param modifytime the value for lccontstate.MODIFYTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }
}