package com.guobao.dto.lis;

import java.math.BigDecimal;

public class LdOccupAtion_Lis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.OCCUPATIONCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String occupationcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.OCCUPATIONTYPE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String occupationtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.WORKTYPE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String worktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.MEDRATE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private BigDecimal medrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.SUDDRISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String suddrisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.DISEARISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String disearisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.HOSIPRISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String hosiprisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.OCCUPATIONVER
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String occupationver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.OCCUPBIGCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String occupbigcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.OCCUPMIDCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String occupmidcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldoccupation.OCCUPLEVEL
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    private String occuplevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.OCCUPATIONCODE
     *
     * @return the value of ldoccupation.OCCUPATIONCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getOccupationcode() {
        return occupationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.OCCUPATIONCODE
     *
     * @param occupationcode the value for ldoccupation.OCCUPATIONCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setOccupationcode(String occupationcode) {
        this.occupationcode = occupationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.OCCUPATIONTYPE
     *
     * @return the value of ldoccupation.OCCUPATIONTYPE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getOccupationtype() {
        return occupationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.OCCUPATIONTYPE
     *
     * @param occupationtype the value for ldoccupation.OCCUPATIONTYPE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setOccupationtype(String occupationtype) {
        this.occupationtype = occupationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.WORKTYPE
     *
     * @return the value of ldoccupation.WORKTYPE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getWorktype() {
        return worktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.WORKTYPE
     *
     * @param worktype the value for ldoccupation.WORKTYPE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setWorktype(String worktype) {
        this.worktype = worktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.MEDRATE
     *
     * @return the value of ldoccupation.MEDRATE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public BigDecimal getMedrate() {
        return medrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.MEDRATE
     *
     * @param medrate the value for ldoccupation.MEDRATE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setMedrate(BigDecimal medrate) {
        this.medrate = medrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.SUDDRISK
     *
     * @return the value of ldoccupation.SUDDRISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getSuddrisk() {
        return suddrisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.SUDDRISK
     *
     * @param suddrisk the value for ldoccupation.SUDDRISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setSuddrisk(String suddrisk) {
        this.suddrisk = suddrisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.DISEARISK
     *
     * @return the value of ldoccupation.DISEARISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getDisearisk() {
        return disearisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.DISEARISK
     *
     * @param disearisk the value for ldoccupation.DISEARISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setDisearisk(String disearisk) {
        this.disearisk = disearisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.HOSIPRISK
     *
     * @return the value of ldoccupation.HOSIPRISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getHosiprisk() {
        return hosiprisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.HOSIPRISK
     *
     * @param hosiprisk the value for ldoccupation.HOSIPRISK
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setHosiprisk(String hosiprisk) {
        this.hosiprisk = hosiprisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.OCCUPATIONVER
     *
     * @return the value of ldoccupation.OCCUPATIONVER
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getOccupationver() {
        return occupationver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.OCCUPATIONVER
     *
     * @param occupationver the value for ldoccupation.OCCUPATIONVER
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setOccupationver(String occupationver) {
        this.occupationver = occupationver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.OCCUPBIGCODE
     *
     * @return the value of ldoccupation.OCCUPBIGCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getOccupbigcode() {
        return occupbigcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.OCCUPBIGCODE
     *
     * @param occupbigcode the value for ldoccupation.OCCUPBIGCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setOccupbigcode(String occupbigcode) {
        this.occupbigcode = occupbigcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.OCCUPMIDCODE
     *
     * @return the value of ldoccupation.OCCUPMIDCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getOccupmidcode() {
        return occupmidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.OCCUPMIDCODE
     *
     * @param occupmidcode the value for ldoccupation.OCCUPMIDCODE
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setOccupmidcode(String occupmidcode) {
        this.occupmidcode = occupmidcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldoccupation.OCCUPLEVEL
     *
     * @return the value of ldoccupation.OCCUPLEVEL
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public String getOccuplevel() {
        return occuplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldoccupation.OCCUPLEVEL
     *
     * @param occuplevel the value for ldoccupation.OCCUPLEVEL
     *
     * @mbg.generated Sun Apr 01 11:50:27 CST 2018
     */
    public void setOccuplevel(String occuplevel) {
        this.occuplevel = occuplevel;
    }
}