package com.guobao.dto.lis;

public class LlClaimPolicy_LisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llclaimpolicy.CASENO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    private String caseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llclaimpolicy.CASERELANO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    private String caserelano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llclaimpolicy.CLMNO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    private String clmno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llclaimpolicy.GETDUTYKIND
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    private String getdutykind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llclaimpolicy.POLNO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    private String polno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llclaimpolicy.CASENO
     *
     * @return the value of llclaimpolicy.CASENO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public String getCaseno() {
        return caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llclaimpolicy.CASENO
     *
     * @param caseno the value for llclaimpolicy.CASENO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public void setCaseno(String caseno) {
        this.caseno = caseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llclaimpolicy.CASERELANO
     *
     * @return the value of llclaimpolicy.CASERELANO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public String getCaserelano() {
        return caserelano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llclaimpolicy.CASERELANO
     *
     * @param caserelano the value for llclaimpolicy.CASERELANO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public void setCaserelano(String caserelano) {
        this.caserelano = caserelano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llclaimpolicy.CLMNO
     *
     * @return the value of llclaimpolicy.CLMNO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public String getClmno() {
        return clmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llclaimpolicy.CLMNO
     *
     * @param clmno the value for llclaimpolicy.CLMNO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public void setClmno(String clmno) {
        this.clmno = clmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llclaimpolicy.GETDUTYKIND
     *
     * @return the value of llclaimpolicy.GETDUTYKIND
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public String getGetdutykind() {
        return getdutykind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llclaimpolicy.GETDUTYKIND
     *
     * @param getdutykind the value for llclaimpolicy.GETDUTYKIND
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public void setGetdutykind(String getdutykind) {
        this.getdutykind = getdutykind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llclaimpolicy.POLNO
     *
     * @return the value of llclaimpolicy.POLNO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public String getPolno() {
        return polno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llclaimpolicy.POLNO
     *
     * @param polno the value for llclaimpolicy.POLNO
     *
     * @mbggenerated Tue Apr 10 16:31:45 CST 2018
     */
    public void setPolno(String polno) {
        this.polno = polno;
    }
}