package com.guobao.dto.lis;

import java.math.BigDecimal;
import java.util.Date;

public class LpEdorApp_Lis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORACCEPTNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edoracceptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.OTHERNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String otherno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.OTHERNOTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String othernotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorappname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String apptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.MANAGECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String managecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CHGPREM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private BigDecimal chgprem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CHGAMNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private BigDecimal chgamnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CHGGETAMNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private BigDecimal chggetamnt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.GETMONEY
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private BigDecimal getmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.GETINTEREST
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private BigDecimal getinterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date edorappdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORSTATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BANKCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BANKACCNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String bankaccno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ACCNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String accname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.POSTALADDRESS
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String postaladdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ZIPCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PRINTFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String printflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String appgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.UWSTATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String uwstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.UWGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String uwgrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.UWOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String uwoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.UWDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date uwdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.UWTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String uwtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CONFOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String confoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CONFDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date confdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CONFTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String conftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.OPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.MAKEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.MAKETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.MODIFYDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.MODIFYTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPROVEFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String approveflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPROVEOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String approveoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPROVEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date approvedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPROVETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String approvetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PAYGETNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String paygetname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PERSONID
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String personid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PAYFORM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String payform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.GETFORM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String getform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPROVEGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String approvegrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPPREGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String apppregrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORCONFNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorconfno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BEHALFNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String behalfname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BEHALFIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String behalfidtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BEHALFIDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String behalfidno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BEHALFPHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String behalfphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BEHALFCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String behalfcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPPHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorappphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BEHALFCODECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String behalfcodecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.SWITCHCHNLTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String switchchnltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.SWITCHCHNLNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String switchchnlname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.CURRENCY
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.SCANMANAGECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String scanmanagecom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.SCANOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String scanoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.SCANDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date scandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.SCANTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String scantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ACCEPTOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String acceptoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ACCEPTDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date acceptdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ACCEPTTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String accepttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.APPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date appdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.RECEIVEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date receivedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.LISTCHECKFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String listcheckflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.COMCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String comcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.MODIFYOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String modifyoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ACCEPTWORKDAYS
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Integer acceptworkdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPCHNL
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorappchnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorappno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPIDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorappidno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.EDORAPPIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String edorappidtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.IDEXPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date idexpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.DOCCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String doccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PERSONIDEXPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private Date personidexpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.PERSONIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String personidtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.BANKPROVINCE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String bankprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lpedorapp.ISORIGINALACCOUNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    private String isoriginalaccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORACCEPTNO
     *
     * @return the value of lpedorapp.EDORACCEPTNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdoracceptno() {
        return edoracceptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORACCEPTNO
     *
     * @param edoracceptno the value for lpedorapp.EDORACCEPTNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdoracceptno(String edoracceptno) {
        this.edoracceptno = edoracceptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.OTHERNO
     *
     * @return the value of lpedorapp.OTHERNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getOtherno() {
        return otherno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.OTHERNO
     *
     * @param otherno the value for lpedorapp.OTHERNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setOtherno(String otherno) {
        this.otherno = otherno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.OTHERNOTYPE
     *
     * @return the value of lpedorapp.OTHERNOTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getOthernotype() {
        return othernotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.OTHERNOTYPE
     *
     * @param othernotype the value for lpedorapp.OTHERNOTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setOthernotype(String othernotype) {
        this.othernotype = othernotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPNAME
     *
     * @return the value of lpedorapp.EDORAPPNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorappname() {
        return edorappname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPNAME
     *
     * @param edorappname the value for lpedorapp.EDORAPPNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappname(String edorappname) {
        this.edorappname = edorappname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPTYPE
     *
     * @return the value of lpedorapp.APPTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPTYPE
     *
     * @param apptype the value for lpedorapp.APPTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApptype(String apptype) {
        this.apptype = apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.MANAGECOM
     *
     * @return the value of lpedorapp.MANAGECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getManagecom() {
        return managecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.MANAGECOM
     *
     * @param managecom the value for lpedorapp.MANAGECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setManagecom(String managecom) {
        this.managecom = managecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CHGPREM
     *
     * @return the value of lpedorapp.CHGPREM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public BigDecimal getChgprem() {
        return chgprem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CHGPREM
     *
     * @param chgprem the value for lpedorapp.CHGPREM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setChgprem(BigDecimal chgprem) {
        this.chgprem = chgprem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CHGAMNT
     *
     * @return the value of lpedorapp.CHGAMNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public BigDecimal getChgamnt() {
        return chgamnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CHGAMNT
     *
     * @param chgamnt the value for lpedorapp.CHGAMNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setChgamnt(BigDecimal chgamnt) {
        this.chgamnt = chgamnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CHGGETAMNT
     *
     * @return the value of lpedorapp.CHGGETAMNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public BigDecimal getChggetamnt() {
        return chggetamnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CHGGETAMNT
     *
     * @param chggetamnt the value for lpedorapp.CHGGETAMNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setChggetamnt(BigDecimal chggetamnt) {
        this.chggetamnt = chggetamnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.GETMONEY
     *
     * @return the value of lpedorapp.GETMONEY
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public BigDecimal getGetmoney() {
        return getmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.GETMONEY
     *
     * @param getmoney the value for lpedorapp.GETMONEY
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setGetmoney(BigDecimal getmoney) {
        this.getmoney = getmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.GETINTEREST
     *
     * @return the value of lpedorapp.GETINTEREST
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public BigDecimal getGetinterest() {
        return getinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.GETINTEREST
     *
     * @param getinterest the value for lpedorapp.GETINTEREST
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setGetinterest(BigDecimal getinterest) {
        this.getinterest = getinterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPDATE
     *
     * @return the value of lpedorapp.EDORAPPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getEdorappdate() {
        return edorappdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPDATE
     *
     * @param edorappdate the value for lpedorapp.EDORAPPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappdate(Date edorappdate) {
        this.edorappdate = edorappdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORSTATE
     *
     * @return the value of lpedorapp.EDORSTATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorstate() {
        return edorstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORSTATE
     *
     * @param edorstate the value for lpedorapp.EDORSTATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorstate(String edorstate) {
        this.edorstate = edorstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BANKCODE
     *
     * @return the value of lpedorapp.BANKCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BANKCODE
     *
     * @param bankcode the value for lpedorapp.BANKCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BANKACCNO
     *
     * @return the value of lpedorapp.BANKACCNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBankaccno() {
        return bankaccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BANKACCNO
     *
     * @param bankaccno the value for lpedorapp.BANKACCNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBankaccno(String bankaccno) {
        this.bankaccno = bankaccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ACCNAME
     *
     * @return the value of lpedorapp.ACCNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getAccname() {
        return accname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ACCNAME
     *
     * @param accname the value for lpedorapp.ACCNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAccname(String accname) {
        this.accname = accname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.POSTALADDRESS
     *
     * @return the value of lpedorapp.POSTALADDRESS
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPostaladdress() {
        return postaladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.POSTALADDRESS
     *
     * @param postaladdress the value for lpedorapp.POSTALADDRESS
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPostaladdress(String postaladdress) {
        this.postaladdress = postaladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ZIPCODE
     *
     * @return the value of lpedorapp.ZIPCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ZIPCODE
     *
     * @param zipcode the value for lpedorapp.ZIPCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PHONE
     *
     * @return the value of lpedorapp.PHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PHONE
     *
     * @param phone the value for lpedorapp.PHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PRINTFLAG
     *
     * @return the value of lpedorapp.PRINTFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPrintflag() {
        return printflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PRINTFLAG
     *
     * @param printflag the value for lpedorapp.PRINTFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPrintflag(String printflag) {
        this.printflag = printflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPGRADE
     *
     * @return the value of lpedorapp.APPGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getAppgrade() {
        return appgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPGRADE
     *
     * @param appgrade the value for lpedorapp.APPGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAppgrade(String appgrade) {
        this.appgrade = appgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.UWSTATE
     *
     * @return the value of lpedorapp.UWSTATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getUwstate() {
        return uwstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.UWSTATE
     *
     * @param uwstate the value for lpedorapp.UWSTATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setUwstate(String uwstate) {
        this.uwstate = uwstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.UWGRADE
     *
     * @return the value of lpedorapp.UWGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getUwgrade() {
        return uwgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.UWGRADE
     *
     * @param uwgrade the value for lpedorapp.UWGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setUwgrade(String uwgrade) {
        this.uwgrade = uwgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.UWOPERATOR
     *
     * @return the value of lpedorapp.UWOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getUwoperator() {
        return uwoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.UWOPERATOR
     *
     * @param uwoperator the value for lpedorapp.UWOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setUwoperator(String uwoperator) {
        this.uwoperator = uwoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.UWDATE
     *
     * @return the value of lpedorapp.UWDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getUwdate() {
        return uwdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.UWDATE
     *
     * @param uwdate the value for lpedorapp.UWDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setUwdate(Date uwdate) {
        this.uwdate = uwdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.UWTIME
     *
     * @return the value of lpedorapp.UWTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getUwtime() {
        return uwtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.UWTIME
     *
     * @param uwtime the value for lpedorapp.UWTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setUwtime(String uwtime) {
        this.uwtime = uwtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CONFOPERATOR
     *
     * @return the value of lpedorapp.CONFOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getConfoperator() {
        return confoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CONFOPERATOR
     *
     * @param confoperator the value for lpedorapp.CONFOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setConfoperator(String confoperator) {
        this.confoperator = confoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CONFDATE
     *
     * @return the value of lpedorapp.CONFDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getConfdate() {
        return confdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CONFDATE
     *
     * @param confdate the value for lpedorapp.CONFDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setConfdate(Date confdate) {
        this.confdate = confdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CONFTIME
     *
     * @return the value of lpedorapp.CONFTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getConftime() {
        return conftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CONFTIME
     *
     * @param conftime the value for lpedorapp.CONFTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setConftime(String conftime) {
        this.conftime = conftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.OPERATOR
     *
     * @return the value of lpedorapp.OPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.OPERATOR
     *
     * @param operator the value for lpedorapp.OPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.MAKEDATE
     *
     * @return the value of lpedorapp.MAKEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.MAKEDATE
     *
     * @param makedate the value for lpedorapp.MAKEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.MAKETIME
     *
     * @return the value of lpedorapp.MAKETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.MAKETIME
     *
     * @param maketime the value for lpedorapp.MAKETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setMaketime(String maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.MODIFYDATE
     *
     * @return the value of lpedorapp.MODIFYDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.MODIFYDATE
     *
     * @param modifydate the value for lpedorapp.MODIFYDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.MODIFYTIME
     *
     * @return the value of lpedorapp.MODIFYTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.MODIFYTIME
     *
     * @param modifytime the value for lpedorapp.MODIFYTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPROVEFLAG
     *
     * @return the value of lpedorapp.APPROVEFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getApproveflag() {
        return approveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPROVEFLAG
     *
     * @param approveflag the value for lpedorapp.APPROVEFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApproveflag(String approveflag) {
        this.approveflag = approveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPROVEOPERATOR
     *
     * @return the value of lpedorapp.APPROVEOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getApproveoperator() {
        return approveoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPROVEOPERATOR
     *
     * @param approveoperator the value for lpedorapp.APPROVEOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApproveoperator(String approveoperator) {
        this.approveoperator = approveoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPROVEDATE
     *
     * @return the value of lpedorapp.APPROVEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getApprovedate() {
        return approvedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPROVEDATE
     *
     * @param approvedate the value for lpedorapp.APPROVEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApprovedate(Date approvedate) {
        this.approvedate = approvedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPROVETIME
     *
     * @return the value of lpedorapp.APPROVETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getApprovetime() {
        return approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPROVETIME
     *
     * @param approvetime the value for lpedorapp.APPROVETIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApprovetime(String approvetime) {
        this.approvetime = approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PAYGETNAME
     *
     * @return the value of lpedorapp.PAYGETNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPaygetname() {
        return paygetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PAYGETNAME
     *
     * @param paygetname the value for lpedorapp.PAYGETNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPaygetname(String paygetname) {
        this.paygetname = paygetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PERSONID
     *
     * @return the value of lpedorapp.PERSONID
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPersonid() {
        return personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PERSONID
     *
     * @param personid the value for lpedorapp.PERSONID
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPersonid(String personid) {
        this.personid = personid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PAYFORM
     *
     * @return the value of lpedorapp.PAYFORM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPayform() {
        return payform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PAYFORM
     *
     * @param payform the value for lpedorapp.PAYFORM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPayform(String payform) {
        this.payform = payform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.GETFORM
     *
     * @return the value of lpedorapp.GETFORM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getGetform() {
        return getform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.GETFORM
     *
     * @param getform the value for lpedorapp.GETFORM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setGetform(String getform) {
        this.getform = getform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPROVEGRADE
     *
     * @return the value of lpedorapp.APPROVEGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getApprovegrade() {
        return approvegrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPROVEGRADE
     *
     * @param approvegrade the value for lpedorapp.APPROVEGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApprovegrade(String approvegrade) {
        this.approvegrade = approvegrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPPREGRADE
     *
     * @return the value of lpedorapp.APPPREGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getApppregrade() {
        return apppregrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPPREGRADE
     *
     * @param apppregrade the value for lpedorapp.APPPREGRADE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setApppregrade(String apppregrade) {
        this.apppregrade = apppregrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORCONFNO
     *
     * @return the value of lpedorapp.EDORCONFNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorconfno() {
        return edorconfno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORCONFNO
     *
     * @param edorconfno the value for lpedorapp.EDORCONFNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorconfno(String edorconfno) {
        this.edorconfno = edorconfno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BEHALFNAME
     *
     * @return the value of lpedorapp.BEHALFNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBehalfname() {
        return behalfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BEHALFNAME
     *
     * @param behalfname the value for lpedorapp.BEHALFNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBehalfname(String behalfname) {
        this.behalfname = behalfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BEHALFIDTYPE
     *
     * @return the value of lpedorapp.BEHALFIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBehalfidtype() {
        return behalfidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BEHALFIDTYPE
     *
     * @param behalfidtype the value for lpedorapp.BEHALFIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBehalfidtype(String behalfidtype) {
        this.behalfidtype = behalfidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BEHALFIDNO
     *
     * @return the value of lpedorapp.BEHALFIDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBehalfidno() {
        return behalfidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BEHALFIDNO
     *
     * @param behalfidno the value for lpedorapp.BEHALFIDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBehalfidno(String behalfidno) {
        this.behalfidno = behalfidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BEHALFPHONE
     *
     * @return the value of lpedorapp.BEHALFPHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBehalfphone() {
        return behalfphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BEHALFPHONE
     *
     * @param behalfphone the value for lpedorapp.BEHALFPHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBehalfphone(String behalfphone) {
        this.behalfphone = behalfphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BEHALFCODE
     *
     * @return the value of lpedorapp.BEHALFCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBehalfcode() {
        return behalfcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BEHALFCODE
     *
     * @param behalfcode the value for lpedorapp.BEHALFCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBehalfcode(String behalfcode) {
        this.behalfcode = behalfcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPPHONE
     *
     * @return the value of lpedorapp.EDORAPPPHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorappphone() {
        return edorappphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPPHONE
     *
     * @param edorappphone the value for lpedorapp.EDORAPPPHONE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappphone(String edorappphone) {
        this.edorappphone = edorappphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BEHALFCODECOM
     *
     * @return the value of lpedorapp.BEHALFCODECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBehalfcodecom() {
        return behalfcodecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BEHALFCODECOM
     *
     * @param behalfcodecom the value for lpedorapp.BEHALFCODECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBehalfcodecom(String behalfcodecom) {
        this.behalfcodecom = behalfcodecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.SWITCHCHNLTYPE
     *
     * @return the value of lpedorapp.SWITCHCHNLTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getSwitchchnltype() {
        return switchchnltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.SWITCHCHNLTYPE
     *
     * @param switchchnltype the value for lpedorapp.SWITCHCHNLTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setSwitchchnltype(String switchchnltype) {
        this.switchchnltype = switchchnltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.SWITCHCHNLNAME
     *
     * @return the value of lpedorapp.SWITCHCHNLNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getSwitchchnlname() {
        return switchchnlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.SWITCHCHNLNAME
     *
     * @param switchchnlname the value for lpedorapp.SWITCHCHNLNAME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setSwitchchnlname(String switchchnlname) {
        this.switchchnlname = switchchnlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.CURRENCY
     *
     * @return the value of lpedorapp.CURRENCY
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.CURRENCY
     *
     * @param currency the value for lpedorapp.CURRENCY
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.SCANMANAGECOM
     *
     * @return the value of lpedorapp.SCANMANAGECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getScanmanagecom() {
        return scanmanagecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.SCANMANAGECOM
     *
     * @param scanmanagecom the value for lpedorapp.SCANMANAGECOM
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setScanmanagecom(String scanmanagecom) {
        this.scanmanagecom = scanmanagecom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.SCANOPERATOR
     *
     * @return the value of lpedorapp.SCANOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getScanoperator() {
        return scanoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.SCANOPERATOR
     *
     * @param scanoperator the value for lpedorapp.SCANOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setScanoperator(String scanoperator) {
        this.scanoperator = scanoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.SCANDATE
     *
     * @return the value of lpedorapp.SCANDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getScandate() {
        return scandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.SCANDATE
     *
     * @param scandate the value for lpedorapp.SCANDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setScandate(Date scandate) {
        this.scandate = scandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.SCANTIME
     *
     * @return the value of lpedorapp.SCANTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getScantime() {
        return scantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.SCANTIME
     *
     * @param scantime the value for lpedorapp.SCANTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setScantime(String scantime) {
        this.scantime = scantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ACCEPTOPERATOR
     *
     * @return the value of lpedorapp.ACCEPTOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getAcceptoperator() {
        return acceptoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ACCEPTOPERATOR
     *
     * @param acceptoperator the value for lpedorapp.ACCEPTOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAcceptoperator(String acceptoperator) {
        this.acceptoperator = acceptoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ACCEPTDATE
     *
     * @return the value of lpedorapp.ACCEPTDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getAcceptdate() {
        return acceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ACCEPTDATE
     *
     * @param acceptdate the value for lpedorapp.ACCEPTDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAcceptdate(Date acceptdate) {
        this.acceptdate = acceptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ACCEPTTIME
     *
     * @return the value of lpedorapp.ACCEPTTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getAccepttime() {
        return accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ACCEPTTIME
     *
     * @param accepttime the value for lpedorapp.ACCEPTTIME
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAccepttime(String accepttime) {
        this.accepttime = accepttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.APPDATE
     *
     * @return the value of lpedorapp.APPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getAppdate() {
        return appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.APPDATE
     *
     * @param appdate the value for lpedorapp.APPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAppdate(Date appdate) {
        this.appdate = appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.RECEIVEDATE
     *
     * @return the value of lpedorapp.RECEIVEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getReceivedate() {
        return receivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.RECEIVEDATE
     *
     * @param receivedate the value for lpedorapp.RECEIVEDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setReceivedate(Date receivedate) {
        this.receivedate = receivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.LISTCHECKFLAG
     *
     * @return the value of lpedorapp.LISTCHECKFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getListcheckflag() {
        return listcheckflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.LISTCHECKFLAG
     *
     * @param listcheckflag the value for lpedorapp.LISTCHECKFLAG
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setListcheckflag(String listcheckflag) {
        this.listcheckflag = listcheckflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.COMCODE
     *
     * @return the value of lpedorapp.COMCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getComcode() {
        return comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.COMCODE
     *
     * @param comcode the value for lpedorapp.COMCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setComcode(String comcode) {
        this.comcode = comcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.MODIFYOPERATOR
     *
     * @return the value of lpedorapp.MODIFYOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getModifyoperator() {
        return modifyoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.MODIFYOPERATOR
     *
     * @param modifyoperator the value for lpedorapp.MODIFYOPERATOR
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setModifyoperator(String modifyoperator) {
        this.modifyoperator = modifyoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ACCEPTWORKDAYS
     *
     * @return the value of lpedorapp.ACCEPTWORKDAYS
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Integer getAcceptworkdays() {
        return acceptworkdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ACCEPTWORKDAYS
     *
     * @param acceptworkdays the value for lpedorapp.ACCEPTWORKDAYS
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setAcceptworkdays(Integer acceptworkdays) {
        this.acceptworkdays = acceptworkdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPCHNL
     *
     * @return the value of lpedorapp.EDORAPPCHNL
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorappchnl() {
        return edorappchnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPCHNL
     *
     * @param edorappchnl the value for lpedorapp.EDORAPPCHNL
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappchnl(String edorappchnl) {
        this.edorappchnl = edorappchnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPNO
     *
     * @return the value of lpedorapp.EDORAPPNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorappno() {
        return edorappno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPNO
     *
     * @param edorappno the value for lpedorapp.EDORAPPNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappno(String edorappno) {
        this.edorappno = edorappno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPIDNO
     *
     * @return the value of lpedorapp.EDORAPPIDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorappidno() {
        return edorappidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPIDNO
     *
     * @param edorappidno the value for lpedorapp.EDORAPPIDNO
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappidno(String edorappidno) {
        this.edorappidno = edorappidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.EDORAPPIDTYPE
     *
     * @return the value of lpedorapp.EDORAPPIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getEdorappidtype() {
        return edorappidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.EDORAPPIDTYPE
     *
     * @param edorappidtype the value for lpedorapp.EDORAPPIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setEdorappidtype(String edorappidtype) {
        this.edorappidtype = edorappidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.IDEXPDATE
     *
     * @return the value of lpedorapp.IDEXPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getIdexpdate() {
        return idexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.IDEXPDATE
     *
     * @param idexpdate the value for lpedorapp.IDEXPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setIdexpdate(Date idexpdate) {
        this.idexpdate = idexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.DOCCODE
     *
     * @return the value of lpedorapp.DOCCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getDoccode() {
        return doccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.DOCCODE
     *
     * @param doccode the value for lpedorapp.DOCCODE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setDoccode(String doccode) {
        this.doccode = doccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PERSONIDEXPDATE
     *
     * @return the value of lpedorapp.PERSONIDEXPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public Date getPersonidexpdate() {
        return personidexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PERSONIDEXPDATE
     *
     * @param personidexpdate the value for lpedorapp.PERSONIDEXPDATE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPersonidexpdate(Date personidexpdate) {
        this.personidexpdate = personidexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.PERSONIDTYPE
     *
     * @return the value of lpedorapp.PERSONIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getPersonidtype() {
        return personidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.PERSONIDTYPE
     *
     * @param personidtype the value for lpedorapp.PERSONIDTYPE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setPersonidtype(String personidtype) {
        this.personidtype = personidtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.BANKPROVINCE
     *
     * @return the value of lpedorapp.BANKPROVINCE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getBankprovince() {
        return bankprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.BANKPROVINCE
     *
     * @param bankprovince the value for lpedorapp.BANKPROVINCE
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setBankprovince(String bankprovince) {
        this.bankprovince = bankprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lpedorapp.ISORIGINALACCOUNT
     *
     * @return the value of lpedorapp.ISORIGINALACCOUNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public String getIsoriginalaccount() {
        return isoriginalaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lpedorapp.ISORIGINALACCOUNT
     *
     * @param isoriginalaccount the value for lpedorapp.ISORIGINALACCOUNT
     *
     * @mbggenerated Tue Mar 06 15:04:58 CST 2018
     */
    public void setIsoriginalaccount(String isoriginalaccount) {
        this.isoriginalaccount = isoriginalaccount;
    }
}