package com.guobao.dto.ifpinsure;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LCAppElcImgDetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public LCAppElcImgDetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPrtnoIsNull() {
			addCriterion("PrtNo is null");
			return (Criteria) this;
		}

		public Criteria andPrtnoIsNotNull() {
			addCriterion("PrtNo is not null");
			return (Criteria) this;
		}

		public Criteria andPrtnoEqualTo(String value) {
			addCriterion("PrtNo =", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoNotEqualTo(String value) {
			addCriterion("PrtNo <>", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoGreaterThan(String value) {
			addCriterion("PrtNo >", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoGreaterThanOrEqualTo(String value) {
			addCriterion("PrtNo >=", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoLessThan(String value) {
			addCriterion("PrtNo <", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoLessThanOrEqualTo(String value) {
			addCriterion("PrtNo <=", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoLike(String value) {
			addCriterion("PrtNo like", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoNotLike(String value) {
			addCriterion("PrtNo not like", value, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoIn(List<String> values) {
			addCriterion("PrtNo in", values, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoNotIn(List<String> values) {
			addCriterion("PrtNo not in", values, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoBetween(String value1, String value2) {
			addCriterion("PrtNo between", value1, value2, "prtno");
			return (Criteria) this;
		}

		public Criteria andPrtnoNotBetween(String value1, String value2) {
			addCriterion("PrtNo not between", value1, value2, "prtno");
			return (Criteria) this;
		}

		public Criteria andObjecttypeIsNull() {
			addCriterion("ObjectType is null");
			return (Criteria) this;
		}

		public Criteria andObjecttypeIsNotNull() {
			addCriterion("ObjectType is not null");
			return (Criteria) this;
		}

		public Criteria andObjecttypeEqualTo(String value) {
			addCriterion("ObjectType =", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeNotEqualTo(String value) {
			addCriterion("ObjectType <>", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeGreaterThan(String value) {
			addCriterion("ObjectType >", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeGreaterThanOrEqualTo(String value) {
			addCriterion("ObjectType >=", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeLessThan(String value) {
			addCriterion("ObjectType <", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeLessThanOrEqualTo(String value) {
			addCriterion("ObjectType <=", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeLike(String value) {
			addCriterion("ObjectType like", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeNotLike(String value) {
			addCriterion("ObjectType not like", value, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeIn(List<String> values) {
			addCriterion("ObjectType in", values, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeNotIn(List<String> values) {
			addCriterion("ObjectType not in", values, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeBetween(String value1, String value2) {
			addCriterion("ObjectType between", value1, value2, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjecttypeNotBetween(String value1, String value2) {
			addCriterion("ObjectType not between", value1, value2, "objecttype");
			return (Criteria) this;
		}

		public Criteria andObjectnoIsNull() {
			addCriterion("ObjectNo is null");
			return (Criteria) this;
		}

		public Criteria andObjectnoIsNotNull() {
			addCriterion("ObjectNo is not null");
			return (Criteria) this;
		}

		public Criteria andObjectnoEqualTo(String value) {
			addCriterion("ObjectNo =", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoNotEqualTo(String value) {
			addCriterion("ObjectNo <>", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoGreaterThan(String value) {
			addCriterion("ObjectNo >", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoGreaterThanOrEqualTo(String value) {
			addCriterion("ObjectNo >=", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoLessThan(String value) {
			addCriterion("ObjectNo <", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoLessThanOrEqualTo(String value) {
			addCriterion("ObjectNo <=", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoLike(String value) {
			addCriterion("ObjectNo like", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoNotLike(String value) {
			addCriterion("ObjectNo not like", value, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoIn(List<String> values) {
			addCriterion("ObjectNo in", values, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoNotIn(List<String> values) {
			addCriterion("ObjectNo not in", values, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoBetween(String value1, String value2) {
			addCriterion("ObjectNo between", value1, value2, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectnoNotBetween(String value1, String value2) {
			addCriterion("ObjectNo not between", value1, value2, "objectno");
			return (Criteria) this;
		}

		public Criteria andObjectidIsNull() {
			addCriterion("ObjectId is null");
			return (Criteria) this;
		}

		public Criteria andObjectidIsNotNull() {
			addCriterion("ObjectId is not null");
			return (Criteria) this;
		}

		public Criteria andObjectidEqualTo(String value) {
			addCriterion("ObjectId =", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidNotEqualTo(String value) {
			addCriterion("ObjectId <>", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidGreaterThan(String value) {
			addCriterion("ObjectId >", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidGreaterThanOrEqualTo(String value) {
			addCriterion("ObjectId >=", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidLessThan(String value) {
			addCriterion("ObjectId <", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidLessThanOrEqualTo(String value) {
			addCriterion("ObjectId <=", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidLike(String value) {
			addCriterion("ObjectId like", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidNotLike(String value) {
			addCriterion("ObjectId not like", value, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidIn(List<String> values) {
			addCriterion("ObjectId in", values, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidNotIn(List<String> values) {
			addCriterion("ObjectId not in", values, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidBetween(String value1, String value2) {
			addCriterion("ObjectId between", value1, value2, "objectid");
			return (Criteria) this;
		}

		public Criteria andObjectidNotBetween(String value1, String value2) {
			addCriterion("ObjectId not between", value1, value2, "objectid");
			return (Criteria) this;
		}

		public Criteria andMakedateIsNull() {
			addCriterion("MakeDate is null");
			return (Criteria) this;
		}

		public Criteria andMakedateIsNotNull() {
			addCriterion("MakeDate is not null");
			return (Criteria) this;
		}

		public Criteria andMakedateEqualTo(Date value) {
			addCriterion("MakeDate =", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateNotEqualTo(Date value) {
			addCriterion("MakeDate <>", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateGreaterThan(Date value) {
			addCriterion("MakeDate >", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateGreaterThanOrEqualTo(Date value) {
			addCriterion("MakeDate >=", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateLessThan(Date value) {
			addCriterion("MakeDate <", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateLessThanOrEqualTo(Date value) {
			addCriterion("MakeDate <=", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateIn(List<Date> values) {
			addCriterion("MakeDate in", values, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateNotIn(List<Date> values) {
			addCriterion("MakeDate not in", values, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateBetween(Date value1, Date value2) {
			addCriterion("MakeDate between", value1, value2, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateNotBetween(Date value1, Date value2) {
			addCriterion("MakeDate not between", value1, value2, "makedate");
			return (Criteria) this;
		}

		public Criteria andModifydateIsNull() {
			addCriterion("ModifyDate is null");
			return (Criteria) this;
		}

		public Criteria andModifydateIsNotNull() {
			addCriterion("ModifyDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifydateEqualTo(Date value) {
			addCriterion("ModifyDate =", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotEqualTo(Date value) {
			addCriterion("ModifyDate <>", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateGreaterThan(Date value) {
			addCriterion("ModifyDate >", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
			addCriterion("ModifyDate >=", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateLessThan(Date value) {
			addCriterion("ModifyDate <", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateLessThanOrEqualTo(Date value) {
			addCriterion("ModifyDate <=", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateIn(List<Date> values) {
			addCriterion("ModifyDate in", values, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotIn(List<Date> values) {
			addCriterion("ModifyDate not in", values, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateBetween(Date value1, Date value2) {
			addCriterion("ModifyDate between", value1, value2, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotBetween(Date value1, Date value2) {
			addCriterion("ModifyDate not between", value1, value2, "modifydate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table lcappelcimgdetail
	 * @mbg.generated  Tue Dec 18 16:49:09 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lcappelcimgdetail
     *
     * @mbggenerated do_not_delete_during_merge Sat Jul 14 09:47:04 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}