package com.guobao.dto.ifpinsure;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LySendToHdExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public LySendToHdExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andReqseqidIsNull() {
			addCriterion("ReqSeqID is null");
			return (Criteria) this;
		}

		public Criteria andReqseqidIsNotNull() {
			addCriterion("ReqSeqID is not null");
			return (Criteria) this;
		}

		public Criteria andReqseqidEqualTo(String value) {
			addCriterion("ReqSeqID =", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidNotEqualTo(String value) {
			addCriterion("ReqSeqID <>", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidGreaterThan(String value) {
			addCriterion("ReqSeqID >", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidGreaterThanOrEqualTo(String value) {
			addCriterion("ReqSeqID >=", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidLessThan(String value) {
			addCriterion("ReqSeqID <", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidLessThanOrEqualTo(String value) {
			addCriterion("ReqSeqID <=", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidLike(String value) {
			addCriterion("ReqSeqID like", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidNotLike(String value) {
			addCriterion("ReqSeqID not like", value, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidIn(List<String> values) {
			addCriterion("ReqSeqID in", values, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidNotIn(List<String> values) {
			addCriterion("ReqSeqID not in", values, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidBetween(String value1, String value2) {
			addCriterion("ReqSeqID between", value1, value2, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andReqseqidNotBetween(String value1, String value2) {
			addCriterion("ReqSeqID not between", value1, value2, "reqseqid");
			return (Criteria) this;
		}

		public Criteria andRdseqIsNull() {
			addCriterion("RdSeq is null");
			return (Criteria) this;
		}

		public Criteria andRdseqIsNotNull() {
			addCriterion("RdSeq is not null");
			return (Criteria) this;
		}

		public Criteria andRdseqEqualTo(String value) {
			addCriterion("RdSeq =", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqNotEqualTo(String value) {
			addCriterion("RdSeq <>", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqGreaterThan(String value) {
			addCriterion("RdSeq >", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqGreaterThanOrEqualTo(String value) {
			addCriterion("RdSeq >=", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqLessThan(String value) {
			addCriterion("RdSeq <", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqLessThanOrEqualTo(String value) {
			addCriterion("RdSeq <=", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqLike(String value) {
			addCriterion("RdSeq like", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqNotLike(String value) {
			addCriterion("RdSeq not like", value, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqIn(List<String> values) {
			addCriterion("RdSeq in", values, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqNotIn(List<String> values) {
			addCriterion("RdSeq not in", values, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqBetween(String value1, String value2) {
			addCriterion("RdSeq between", value1, value2, "rdseq");
			return (Criteria) this;
		}

		public Criteria andRdseqNotBetween(String value1, String value2) {
			addCriterion("RdSeq not between", value1, value2, "rdseq");
			return (Criteria) this;
		}

		public Criteria andSerialnoIsNull() {
			addCriterion("SerialNo is null");
			return (Criteria) this;
		}

		public Criteria andSerialnoIsNotNull() {
			addCriterion("SerialNo is not null");
			return (Criteria) this;
		}

		public Criteria andSerialnoEqualTo(String value) {
			addCriterion("SerialNo =", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotEqualTo(String value) {
			addCriterion("SerialNo <>", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoGreaterThan(String value) {
			addCriterion("SerialNo >", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoGreaterThanOrEqualTo(String value) {
			addCriterion("SerialNo >=", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLessThan(String value) {
			addCriterion("SerialNo <", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLessThanOrEqualTo(String value) {
			addCriterion("SerialNo <=", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoLike(String value) {
			addCriterion("SerialNo like", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotLike(String value) {
			addCriterion("SerialNo not like", value, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoIn(List<String> values) {
			addCriterion("SerialNo in", values, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotIn(List<String> values) {
			addCriterion("SerialNo not in", values, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoBetween(String value1, String value2) {
			addCriterion("SerialNo between", value1, value2, "serialno");
			return (Criteria) this;
		}

		public Criteria andSerialnoNotBetween(String value1, String value2) {
			addCriterion("SerialNo not between", value1, value2, "serialno");
			return (Criteria) this;
		}

		public Criteria andPaycodeIsNull() {
			addCriterion("PayCode is null");
			return (Criteria) this;
		}

		public Criteria andPaycodeIsNotNull() {
			addCriterion("PayCode is not null");
			return (Criteria) this;
		}

		public Criteria andPaycodeEqualTo(String value) {
			addCriterion("PayCode =", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeNotEqualTo(String value) {
			addCriterion("PayCode <>", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeGreaterThan(String value) {
			addCriterion("PayCode >", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeGreaterThanOrEqualTo(String value) {
			addCriterion("PayCode >=", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeLessThan(String value) {
			addCriterion("PayCode <", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeLessThanOrEqualTo(String value) {
			addCriterion("PayCode <=", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeLike(String value) {
			addCriterion("PayCode like", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeNotLike(String value) {
			addCriterion("PayCode not like", value, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeIn(List<String> values) {
			addCriterion("PayCode in", values, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeNotIn(List<String> values) {
			addCriterion("PayCode not in", values, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeBetween(String value1, String value2) {
			addCriterion("PayCode between", value1, value2, "paycode");
			return (Criteria) this;
		}

		public Criteria andPaycodeNotBetween(String value1, String value2) {
			addCriterion("PayCode not between", value1, value2, "paycode");
			return (Criteria) this;
		}

		public Criteria andOthernoIsNull() {
			addCriterion("OtherNo is null");
			return (Criteria) this;
		}

		public Criteria andOthernoIsNotNull() {
			addCriterion("OtherNo is not null");
			return (Criteria) this;
		}

		public Criteria andOthernoEqualTo(String value) {
			addCriterion("OtherNo =", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoNotEqualTo(String value) {
			addCriterion("OtherNo <>", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoGreaterThan(String value) {
			addCriterion("OtherNo >", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoGreaterThanOrEqualTo(String value) {
			addCriterion("OtherNo >=", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoLessThan(String value) {
			addCriterion("OtherNo <", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoLessThanOrEqualTo(String value) {
			addCriterion("OtherNo <=", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoLike(String value) {
			addCriterion("OtherNo like", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoNotLike(String value) {
			addCriterion("OtherNo not like", value, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoIn(List<String> values) {
			addCriterion("OtherNo in", values, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoNotIn(List<String> values) {
			addCriterion("OtherNo not in", values, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoBetween(String value1, String value2) {
			addCriterion("OtherNo between", value1, value2, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernoNotBetween(String value1, String value2) {
			addCriterion("OtherNo not between", value1, value2, "otherno");
			return (Criteria) this;
		}

		public Criteria andOthernotypeIsNull() {
			addCriterion("OthernoType is null");
			return (Criteria) this;
		}

		public Criteria andOthernotypeIsNotNull() {
			addCriterion("OthernoType is not null");
			return (Criteria) this;
		}

		public Criteria andOthernotypeEqualTo(String value) {
			addCriterion("OthernoType =", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeNotEqualTo(String value) {
			addCriterion("OthernoType <>", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeGreaterThan(String value) {
			addCriterion("OthernoType >", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeGreaterThanOrEqualTo(String value) {
			addCriterion("OthernoType >=", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeLessThan(String value) {
			addCriterion("OthernoType <", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeLessThanOrEqualTo(String value) {
			addCriterion("OthernoType <=", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeLike(String value) {
			addCriterion("OthernoType like", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeNotLike(String value) {
			addCriterion("OthernoType not like", value, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeIn(List<String> values) {
			addCriterion("OthernoType in", values, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeNotIn(List<String> values) {
			addCriterion("OthernoType not in", values, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeBetween(String value1, String value2) {
			addCriterion("OthernoType between", value1, value2, "othernotype");
			return (Criteria) this;
		}

		public Criteria andOthernotypeNotBetween(String value1, String value2) {
			addCriterion("OthernoType not between", value1, value2, "othernotype");
			return (Criteria) this;
		}

		public Criteria andMesscodeIsNull() {
			addCriterion("MessCode is null");
			return (Criteria) this;
		}

		public Criteria andMesscodeIsNotNull() {
			addCriterion("MessCode is not null");
			return (Criteria) this;
		}

		public Criteria andMesscodeEqualTo(String value) {
			addCriterion("MessCode =", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeNotEqualTo(String value) {
			addCriterion("MessCode <>", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeGreaterThan(String value) {
			addCriterion("MessCode >", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeGreaterThanOrEqualTo(String value) {
			addCriterion("MessCode >=", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeLessThan(String value) {
			addCriterion("MessCode <", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeLessThanOrEqualTo(String value) {
			addCriterion("MessCode <=", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeLike(String value) {
			addCriterion("MessCode like", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeNotLike(String value) {
			addCriterion("MessCode not like", value, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeIn(List<String> values) {
			addCriterion("MessCode in", values, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeNotIn(List<String> values) {
			addCriterion("MessCode not in", values, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeBetween(String value1, String value2) {
			addCriterion("MessCode between", value1, value2, "messcode");
			return (Criteria) this;
		}

		public Criteria andMesscodeNotBetween(String value1, String value2) {
			addCriterion("MessCode not between", value1, value2, "messcode");
			return (Criteria) this;
		}

		public Criteria andMessinfoIsNull() {
			addCriterion("MessInfo is null");
			return (Criteria) this;
		}

		public Criteria andMessinfoIsNotNull() {
			addCriterion("MessInfo is not null");
			return (Criteria) this;
		}

		public Criteria andMessinfoEqualTo(String value) {
			addCriterion("MessInfo =", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoNotEqualTo(String value) {
			addCriterion("MessInfo <>", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoGreaterThan(String value) {
			addCriterion("MessInfo >", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoGreaterThanOrEqualTo(String value) {
			addCriterion("MessInfo >=", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoLessThan(String value) {
			addCriterion("MessInfo <", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoLessThanOrEqualTo(String value) {
			addCriterion("MessInfo <=", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoLike(String value) {
			addCriterion("MessInfo like", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoNotLike(String value) {
			addCriterion("MessInfo not like", value, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoIn(List<String> values) {
			addCriterion("MessInfo in", values, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoNotIn(List<String> values) {
			addCriterion("MessInfo not in", values, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoBetween(String value1, String value2) {
			addCriterion("MessInfo between", value1, value2, "messinfo");
			return (Criteria) this;
		}

		public Criteria andMessinfoNotBetween(String value1, String value2) {
			addCriterion("MessInfo not between", value1, value2, "messinfo");
			return (Criteria) this;
		}

		public Criteria andTransstateIsNull() {
			addCriterion("TransState is null");
			return (Criteria) this;
		}

		public Criteria andTransstateIsNotNull() {
			addCriterion("TransState is not null");
			return (Criteria) this;
		}

		public Criteria andTransstateEqualTo(String value) {
			addCriterion("TransState =", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateNotEqualTo(String value) {
			addCriterion("TransState <>", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateGreaterThan(String value) {
			addCriterion("TransState >", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateGreaterThanOrEqualTo(String value) {
			addCriterion("TransState >=", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateLessThan(String value) {
			addCriterion("TransState <", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateLessThanOrEqualTo(String value) {
			addCriterion("TransState <=", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateLike(String value) {
			addCriterion("TransState like", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateNotLike(String value) {
			addCriterion("TransState not like", value, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateIn(List<String> values) {
			addCriterion("TransState in", values, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateNotIn(List<String> values) {
			addCriterion("TransState not in", values, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateBetween(String value1, String value2) {
			addCriterion("TransState between", value1, value2, "transstate");
			return (Criteria) this;
		}

		public Criteria andTransstateNotBetween(String value1, String value2) {
			addCriterion("TransState not between", value1, value2, "transstate");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeIsNull() {
			addCriterion("PayInfoCode is null");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeIsNotNull() {
			addCriterion("PayInfoCode is not null");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeEqualTo(String value) {
			addCriterion("PayInfoCode =", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeNotEqualTo(String value) {
			addCriterion("PayInfoCode <>", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeGreaterThan(String value) {
			addCriterion("PayInfoCode >", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeGreaterThanOrEqualTo(String value) {
			addCriterion("PayInfoCode >=", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeLessThan(String value) {
			addCriterion("PayInfoCode <", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeLessThanOrEqualTo(String value) {
			addCriterion("PayInfoCode <=", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeLike(String value) {
			addCriterion("PayInfoCode like", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeNotLike(String value) {
			addCriterion("PayInfoCode not like", value, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeIn(List<String> values) {
			addCriterion("PayInfoCode in", values, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeNotIn(List<String> values) {
			addCriterion("PayInfoCode not in", values, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeBetween(String value1, String value2) {
			addCriterion("PayInfoCode between", value1, value2, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfocodeNotBetween(String value1, String value2) {
			addCriterion("PayInfoCode not between", value1, value2, "payinfocode");
			return (Criteria) this;
		}

		public Criteria andPayinfoIsNull() {
			addCriterion("PayInfo is null");
			return (Criteria) this;
		}

		public Criteria andPayinfoIsNotNull() {
			addCriterion("PayInfo is not null");
			return (Criteria) this;
		}

		public Criteria andPayinfoEqualTo(String value) {
			addCriterion("PayInfo =", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoNotEqualTo(String value) {
			addCriterion("PayInfo <>", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoGreaterThan(String value) {
			addCriterion("PayInfo >", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoGreaterThanOrEqualTo(String value) {
			addCriterion("PayInfo >=", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoLessThan(String value) {
			addCriterion("PayInfo <", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoLessThanOrEqualTo(String value) {
			addCriterion("PayInfo <=", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoLike(String value) {
			addCriterion("PayInfo like", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoNotLike(String value) {
			addCriterion("PayInfo not like", value, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoIn(List<String> values) {
			addCriterion("PayInfo in", values, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoNotIn(List<String> values) {
			addCriterion("PayInfo not in", values, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoBetween(String value1, String value2) {
			addCriterion("PayInfo between", value1, value2, "payinfo");
			return (Criteria) this;
		}

		public Criteria andPayinfoNotBetween(String value1, String value2) {
			addCriterion("PayInfo not between", value1, value2, "payinfo");
			return (Criteria) this;
		}

		public Criteria andFailtypeIsNull() {
			addCriterion("FailType is null");
			return (Criteria) this;
		}

		public Criteria andFailtypeIsNotNull() {
			addCriterion("FailType is not null");
			return (Criteria) this;
		}

		public Criteria andFailtypeEqualTo(String value) {
			addCriterion("FailType =", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeNotEqualTo(String value) {
			addCriterion("FailType <>", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeGreaterThan(String value) {
			addCriterion("FailType >", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeGreaterThanOrEqualTo(String value) {
			addCriterion("FailType >=", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeLessThan(String value) {
			addCriterion("FailType <", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeLessThanOrEqualTo(String value) {
			addCriterion("FailType <=", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeLike(String value) {
			addCriterion("FailType like", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeNotLike(String value) {
			addCriterion("FailType not like", value, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeIn(List<String> values) {
			addCriterion("FailType in", values, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeNotIn(List<String> values) {
			addCriterion("FailType not in", values, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeBetween(String value1, String value2) {
			addCriterion("FailType between", value1, value2, "failtype");
			return (Criteria) this;
		}

		public Criteria andFailtypeNotBetween(String value1, String value2) {
			addCriterion("FailType not between", value1, value2, "failtype");
			return (Criteria) this;
		}

		public Criteria andPaymadedateIsNull() {
			addCriterion("PayMadeDate is null");
			return (Criteria) this;
		}

		public Criteria andPaymadedateIsNotNull() {
			addCriterion("PayMadeDate is not null");
			return (Criteria) this;
		}

		public Criteria andPaymadedateEqualTo(Date value) {
			addCriterionForJDBCDate("PayMadeDate =", value, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateNotEqualTo(Date value) {
			addCriterionForJDBCDate("PayMadeDate <>", value, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateGreaterThan(Date value) {
			addCriterionForJDBCDate("PayMadeDate >", value, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PayMadeDate >=", value, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateLessThan(Date value) {
			addCriterionForJDBCDate("PayMadeDate <", value, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("PayMadeDate <=", value, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateIn(List<Date> values) {
			addCriterionForJDBCDate("PayMadeDate in", values, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateNotIn(List<Date> values) {
			addCriterionForJDBCDate("PayMadeDate not in", values, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PayMadeDate between", value1, value2, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andPaymadedateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("PayMadeDate not between", value1, value2, "paymadedate");
			return (Criteria) this;
		}

		public Criteria andAbstractnoIsNull() {
			addCriterion("AbstractNo is null");
			return (Criteria) this;
		}

		public Criteria andAbstractnoIsNotNull() {
			addCriterion("AbstractNo is not null");
			return (Criteria) this;
		}

		public Criteria andAbstractnoEqualTo(String value) {
			addCriterion("AbstractNo =", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoNotEqualTo(String value) {
			addCriterion("AbstractNo <>", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoGreaterThan(String value) {
			addCriterion("AbstractNo >", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoGreaterThanOrEqualTo(String value) {
			addCriterion("AbstractNo >=", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoLessThan(String value) {
			addCriterion("AbstractNo <", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoLessThanOrEqualTo(String value) {
			addCriterion("AbstractNo <=", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoLike(String value) {
			addCriterion("AbstractNo like", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoNotLike(String value) {
			addCriterion("AbstractNo not like", value, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoIn(List<String> values) {
			addCriterion("AbstractNo in", values, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoNotIn(List<String> values) {
			addCriterion("AbstractNo not in", values, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoBetween(String value1, String value2) {
			addCriterion("AbstractNo between", value1, value2, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAbstractnoNotBetween(String value1, String value2) {
			addCriterion("AbstractNo not between", value1, value2, "abstractno");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("Amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("Amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(String value) {
			addCriterion("Amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(String value) {
			addCriterion("Amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(String value) {
			addCriterion("Amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(String value) {
			addCriterion("Amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(String value) {
			addCriterion("Amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(String value) {
			addCriterion("Amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLike(String value) {
			addCriterion("Amount like", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotLike(String value) {
			addCriterion("Amount not like", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<String> values) {
			addCriterion("Amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<String> values) {
			addCriterion("Amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(String value1, String value2) {
			addCriterion("Amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(String value1, String value2) {
			addCriterion("Amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andMakedateIsNull() {
			addCriterion("MakeDate is null");
			return (Criteria) this;
		}

		public Criteria andMakedateIsNotNull() {
			addCriterion("MakeDate is not null");
			return (Criteria) this;
		}

		public Criteria andMakedateEqualTo(Date value) {
			addCriterionForJDBCDate("MakeDate =", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateNotEqualTo(Date value) {
			addCriterionForJDBCDate("MakeDate <>", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateGreaterThan(Date value) {
			addCriterionForJDBCDate("MakeDate >", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("MakeDate >=", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateLessThan(Date value) {
			addCriterionForJDBCDate("MakeDate <", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("MakeDate <=", value, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateIn(List<Date> values) {
			addCriterionForJDBCDate("MakeDate in", values, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateNotIn(List<Date> values) {
			addCriterionForJDBCDate("MakeDate not in", values, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("MakeDate between", value1, value2, "makedate");
			return (Criteria) this;
		}

		public Criteria andMakedateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("MakeDate not between", value1, value2, "makedate");
			return (Criteria) this;
		}

		public Criteria andMaketimeIsNull() {
			addCriterion("MakeTime is null");
			return (Criteria) this;
		}

		public Criteria andMaketimeIsNotNull() {
			addCriterion("MakeTime is not null");
			return (Criteria) this;
		}

		public Criteria andMaketimeEqualTo(String value) {
			addCriterion("MakeTime =", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeNotEqualTo(String value) {
			addCriterion("MakeTime <>", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeGreaterThan(String value) {
			addCriterion("MakeTime >", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeGreaterThanOrEqualTo(String value) {
			addCriterion("MakeTime >=", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeLessThan(String value) {
			addCriterion("MakeTime <", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeLessThanOrEqualTo(String value) {
			addCriterion("MakeTime <=", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeLike(String value) {
			addCriterion("MakeTime like", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeNotLike(String value) {
			addCriterion("MakeTime not like", value, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeIn(List<String> values) {
			addCriterion("MakeTime in", values, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeNotIn(List<String> values) {
			addCriterion("MakeTime not in", values, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeBetween(String value1, String value2) {
			addCriterion("MakeTime between", value1, value2, "maketime");
			return (Criteria) this;
		}

		public Criteria andMaketimeNotBetween(String value1, String value2) {
			addCriterion("MakeTime not between", value1, value2, "maketime");
			return (Criteria) this;
		}

		public Criteria andModifydateIsNull() {
			addCriterion("ModifyDate is null");
			return (Criteria) this;
		}

		public Criteria andModifydateIsNotNull() {
			addCriterion("ModifyDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifydateEqualTo(Date value) {
			addCriterionForJDBCDate("ModifyDate =", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotEqualTo(Date value) {
			addCriterionForJDBCDate("ModifyDate <>", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateGreaterThan(Date value) {
			addCriterionForJDBCDate("ModifyDate >", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ModifyDate >=", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateLessThan(Date value) {
			addCriterionForJDBCDate("ModifyDate <", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ModifyDate <=", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateIn(List<Date> values) {
			addCriterionForJDBCDate("ModifyDate in", values, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotIn(List<Date> values) {
			addCriterionForJDBCDate("ModifyDate not in", values, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ModifyDate between", value1, value2, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ModifyDate not between", value1, value2, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNull() {
			addCriterion("ModifyTime is null");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNotNull() {
			addCriterion("ModifyTime is not null");
			return (Criteria) this;
		}

		public Criteria andModifytimeEqualTo(String value) {
			addCriterion("ModifyTime =", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotEqualTo(String value) {
			addCriterion("ModifyTime <>", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThan(String value) {
			addCriterion("ModifyTime >", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThanOrEqualTo(String value) {
			addCriterion("ModifyTime >=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThan(String value) {
			addCriterion("ModifyTime <", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThanOrEqualTo(String value) {
			addCriterion("ModifyTime <=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLike(String value) {
			addCriterion("ModifyTime like", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotLike(String value) {
			addCriterion("ModifyTime not like", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeIn(List<String> values) {
			addCriterion("ModifyTime in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotIn(List<String> values) {
			addCriterion("ModifyTime not in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeBetween(String value1, String value2) {
			addCriterion("ModifyTime between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotBetween(String value1, String value2) {
			addCriterion("ModifyTime not between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andInbankcodeIsNull() {
			addCriterion("InBankCode is null");
			return (Criteria) this;
		}

		public Criteria andInbankcodeIsNotNull() {
			addCriterion("InBankCode is not null");
			return (Criteria) this;
		}

		public Criteria andInbankcodeEqualTo(String value) {
			addCriterion("InBankCode =", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeNotEqualTo(String value) {
			addCriterion("InBankCode <>", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeGreaterThan(String value) {
			addCriterion("InBankCode >", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeGreaterThanOrEqualTo(String value) {
			addCriterion("InBankCode >=", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeLessThan(String value) {
			addCriterion("InBankCode <", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeLessThanOrEqualTo(String value) {
			addCriterion("InBankCode <=", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeLike(String value) {
			addCriterion("InBankCode like", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeNotLike(String value) {
			addCriterion("InBankCode not like", value, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeIn(List<String> values) {
			addCriterion("InBankCode in", values, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeNotIn(List<String> values) {
			addCriterion("InBankCode not in", values, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeBetween(String value1, String value2) {
			addCriterion("InBankCode between", value1, value2, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankcodeNotBetween(String value1, String value2) {
			addCriterion("InBankCode not between", value1, value2, "inbankcode");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoIsNull() {
			addCriterion("InBankAccNO is null");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoIsNotNull() {
			addCriterion("InBankAccNO is not null");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoEqualTo(String value) {
			addCriterion("InBankAccNO =", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoNotEqualTo(String value) {
			addCriterion("InBankAccNO <>", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoGreaterThan(String value) {
			addCriterion("InBankAccNO >", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoGreaterThanOrEqualTo(String value) {
			addCriterion("InBankAccNO >=", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoLessThan(String value) {
			addCriterion("InBankAccNO <", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoLessThanOrEqualTo(String value) {
			addCriterion("InBankAccNO <=", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoLike(String value) {
			addCriterion("InBankAccNO like", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoNotLike(String value) {
			addCriterion("InBankAccNO not like", value, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoIn(List<String> values) {
			addCriterion("InBankAccNO in", values, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoNotIn(List<String> values) {
			addCriterion("InBankAccNO not in", values, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoBetween(String value1, String value2) {
			addCriterion("InBankAccNO between", value1, value2, "inbankaccno");
			return (Criteria) this;
		}

		public Criteria andInbankaccnoNotBetween(String value1, String value2) {
			addCriterion("InBankAccNO not between", value1, value2, "inbankaccno");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table lysendtohd
	 * @mbg.generated  Mon Dec 17 18:14:40 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lysendtohd
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 23 09:32:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}