package com.guobao.dto.product;

public class LmRiskRela extends LmRiskRelaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lmriskrela.DKSUBPREM
     *
     * @mbg.generated Mon Nov 12 11:18:10 CST 2018
     */
    private String dksubprem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lmriskrela.DKSUBPREM
     *
     * @return the value of lmriskrela.DKSUBPREM
     *
     * @mbg.generated Mon Nov 12 11:18:10 CST 2018
     */
    public String getDksubprem() {
        return dksubprem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lmriskrela.DKSUBPREM
     *
     * @param dksubprem the value for lmriskrela.DKSUBPREM
     *
     * @mbg.generated Mon Nov 12 11:18:10 CST 2018
     */
    public void setDksubprem(String dksubprem) {
        this.dksubprem = dksubprem;
    }
}