package com.guobao.dto.bq;

import java.util.Date;

public class LcConThangupState extends LcConThangupStateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.HANGUPNO
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String hangupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.NBFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String nbflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.POSFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String posflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.CLAIMFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String claimflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.AGENTFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String agentflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.RNFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String rnflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.STANDFLAG1
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String standflag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.STANDFLAG2
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String standflag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.STANDFLAG3
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String standflag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.OPERATOR
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.MAKEDATE
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.MAKETIME
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.MODIFYDATE
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.MODIFYTIME
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.STANDFLAG4
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String standflag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.STANDFLAG5
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String standflag5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.MODIFYOPERATOR
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String modifyoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lcconthangupstate.REMARK
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.HANGUPNO
     *
     * @return the value of lcconthangupstate.HANGUPNO
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getHangupno() {
        return hangupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.HANGUPNO
     *
     * @param hangupno the value for lcconthangupstate.HANGUPNO
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setHangupno(String hangupno) {
        this.hangupno = hangupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.NBFLAG
     *
     * @return the value of lcconthangupstate.NBFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getNbflag() {
        return nbflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.NBFLAG
     *
     * @param nbflag the value for lcconthangupstate.NBFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setNbflag(String nbflag) {
        this.nbflag = nbflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.POSFLAG
     *
     * @return the value of lcconthangupstate.POSFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getPosflag() {
        return posflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.POSFLAG
     *
     * @param posflag the value for lcconthangupstate.POSFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setPosflag(String posflag) {
        this.posflag = posflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.CLAIMFLAG
     *
     * @return the value of lcconthangupstate.CLAIMFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getClaimflag() {
        return claimflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.CLAIMFLAG
     *
     * @param claimflag the value for lcconthangupstate.CLAIMFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setClaimflag(String claimflag) {
        this.claimflag = claimflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.AGENTFLAG
     *
     * @return the value of lcconthangupstate.AGENTFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getAgentflag() {
        return agentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.AGENTFLAG
     *
     * @param agentflag the value for lcconthangupstate.AGENTFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setAgentflag(String agentflag) {
        this.agentflag = agentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.RNFLAG
     *
     * @return the value of lcconthangupstate.RNFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getRnflag() {
        return rnflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.RNFLAG
     *
     * @param rnflag the value for lcconthangupstate.RNFLAG
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setRnflag(String rnflag) {
        this.rnflag = rnflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.STANDFLAG1
     *
     * @return the value of lcconthangupstate.STANDFLAG1
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getStandflag1() {
        return standflag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.STANDFLAG1
     *
     * @param standflag1 the value for lcconthangupstate.STANDFLAG1
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setStandflag1(String standflag1) {
        this.standflag1 = standflag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.STANDFLAG2
     *
     * @return the value of lcconthangupstate.STANDFLAG2
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getStandflag2() {
        return standflag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.STANDFLAG2
     *
     * @param standflag2 the value for lcconthangupstate.STANDFLAG2
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setStandflag2(String standflag2) {
        this.standflag2 = standflag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.STANDFLAG3
     *
     * @return the value of lcconthangupstate.STANDFLAG3
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getStandflag3() {
        return standflag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.STANDFLAG3
     *
     * @param standflag3 the value for lcconthangupstate.STANDFLAG3
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setStandflag3(String standflag3) {
        this.standflag3 = standflag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.OPERATOR
     *
     * @return the value of lcconthangupstate.OPERATOR
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.OPERATOR
     *
     * @param operator the value for lcconthangupstate.OPERATOR
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.MAKEDATE
     *
     * @return the value of lcconthangupstate.MAKEDATE
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.MAKEDATE
     *
     * @param makedate the value for lcconthangupstate.MAKEDATE
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.MAKETIME
     *
     * @return the value of lcconthangupstate.MAKETIME
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.MAKETIME
     *
     * @param maketime the value for lcconthangupstate.MAKETIME
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setMaketime(String maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.MODIFYDATE
     *
     * @return the value of lcconthangupstate.MODIFYDATE
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.MODIFYDATE
     *
     * @param modifydate the value for lcconthangupstate.MODIFYDATE
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.MODIFYTIME
     *
     * @return the value of lcconthangupstate.MODIFYTIME
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.MODIFYTIME
     *
     * @param modifytime the value for lcconthangupstate.MODIFYTIME
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.STANDFLAG4
     *
     * @return the value of lcconthangupstate.STANDFLAG4
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getStandflag4() {
        return standflag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.STANDFLAG4
     *
     * @param standflag4 the value for lcconthangupstate.STANDFLAG4
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setStandflag4(String standflag4) {
        this.standflag4 = standflag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.STANDFLAG5
     *
     * @return the value of lcconthangupstate.STANDFLAG5
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getStandflag5() {
        return standflag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.STANDFLAG5
     *
     * @param standflag5 the value for lcconthangupstate.STANDFLAG5
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setStandflag5(String standflag5) {
        this.standflag5 = standflag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.MODIFYOPERATOR
     *
     * @return the value of lcconthangupstate.MODIFYOPERATOR
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getModifyoperator() {
        return modifyoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.MODIFYOPERATOR
     *
     * @param modifyoperator the value for lcconthangupstate.MODIFYOPERATOR
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setModifyoperator(String modifyoperator) {
        this.modifyoperator = modifyoperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lcconthangupstate.REMARK
     *
     * @return the value of lcconthangupstate.REMARK
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lcconthangupstate.REMARK
     *
     * @param remark the value for lcconthangupstate.REMARK
     *
     * @mbggenerated Wed Feb 28 10:08:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}